export const metadata = {
  title: 'AI Automation in Downtown KC & Crossroads | Small Business Consulting | S.Y.S.T.E.M. KC',
  description: 'Local AI automation consulting for Downtown KC & Crossroads small businesses. In-person audits, fixed-bid builds, monthly retainers that cover your subscriptions. Plain English, no long-term contracts.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">·</span><a href="/">Locations</a><span className="sep">·</span><span className="here">Downtown KC & Crossroads</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">Service area · Jackson County, MO</span><h1>AI automation consulting in <em>Downtown KC & Crossroads</em>.</h1><p className="lede">Crossroads Arts District, Westport, Power & Light, and the creative + tech cluster downtown. We work with the agencies, restaurants, startups, and small professional firms that anchor the city's creative core.</p><div className="actions"><a className="btn btn--primary" href="/contact/">Book a 20-min call <span className="arrow">→</span></a><a className="btn btn--ghost" href="/services/">See services</a></div></div></header>
<section className="section"><div className="wrap"><div className="prose" style={{maxWidth: '72ch'}}><h2 style={{marginTop: '0'}}>Downtown gets the pitch fastest.</h2><p>Downtown KC and the Crossroads are home to the metro's most tech-forward small-business community. Agencies in the Crossroads, restaurants in Westport, and the small professional firms scattered through the Power &amp; Light and Library District buildings tend to already <em>know</em> they should be automating more — they just have not had time to do it themselves.</p><p>That makes the conversation different here. We are not explaining what automation is. <strong>We are picking the three highest-leverage automations out of the eight an owner has been meaning to set up</strong> — and making them real over a two-week build.</p><p>The Crossroads creative community has a unique opportunity: agency-style client communication, automated proofing and approvals, and post-engagement review collection — done well — is rare even in agency culture. We have built it for several KC agencies.</p></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common in Downtown KC & Crossroads</span><h2 style={{marginTop: '14px'}}>Industries we serve here.</h2></div></div><div className="card-grid"><a className="card" href="/industries/restaurant-automation-kansas-city/"><span className="tag">Hospitality</span><h3>Restaurants & food service</h3><p>No-show reduction, review responses, social scheduling.</p><span className="more">Explore →</span></a><a className="card" href="/industries/law-firm-automation-kansas-city/"><span className="tag">Professional</span><h3>Law firms & accounting</h3><p>Intake, document follow-up, billing reminders.</p><span className="more">Explore →</span></a><a className="card" href="/industries/real-estate-automation-kansas-city/"><span className="tag">Property</span><h3>Real estate agents & brokers</h3><p>5-min lead response, nurture sequences, cold-lead resurrection.</p><span className="more">Explore →</span></a><a className="card" href="/industries/salon-spa-automation-kansas-city/"><span className="tag">Beauty</span><h3>Salons, spas & personal care</h3><p>Online booking, no-show reduction, social posts.</p><span className="more">Explore →</span></a><a className="card" href="/industries/medical-dental-automation-kansas-city/"><span className="tag">Health</span><h3>Medical, dental & clinics</h3><p>Appointment reminders, patient intake, review collection.</p><span className="more">Explore →</span></a><a className="card" href="/industries/hvac-plumbing-automation-kansas-city/"><span className="tag">Trades</span><h3>HVAC, plumbing & home services</h3><p>Missed-call text-back, quote follow-up, review automation.</p><span className="more">Explore →</span></a></div></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="label">How we work</span><h2 style={{marginTop: '14px'}}>The same in Downtown KC & Crossroads as everywhere.</h2></div></div><div className="card-grid card-grid--2"><div className="card"><span className="tag">Step 01</span><h3>$397 audit</h3><p>2–3 hours in your business. Ranked, written plan of every leak. Yours whether you DIY, hire us to teach you, or hire us to build it.</p></div><div className="card"><span className="tag">Step 02 (optional)</span><h3>Teach or Build</h3><p>You pick. Side-by-side training to run it yourself, or a fixed-bid done-for-you build starting at $500.</p></div></div></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Find your <em>leaks</em>, Downtown KC & Crossroads.</h2><p className="sub">We drive to your business — same day for emergencies, this week for the rest. Downtown KC and the Crossroads are 0 miles from our base.</p><div className="actions"><a className="btn btn--invert" href="/contact/">Book a call <span className="arrow">→</span></a><a className="btn btn--ghost-invert" href="/services/system-audit-kansas-city/">Or book the audit</a></div></div></section>
    </main>
  );
}