export const metadata = {
  title: 'AI Automation in Lee\'s Summit | Small Business Consulting | S.Y.S.T.E.M. KC',
  description: 'Local AI automation consulting for Lee\'s Summit small businesses. In-person audits, fixed-bid builds, monthly retainers that cover your subscriptions. Plain English, no long-term contracts.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">·</span><a href="/">Locations</a><span className="sep">·</span><span className="here">Lee's Summit</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">Service area · Eastern Jackson County, MO</span><h1>AI automation consulting in <em>Lee's Summit</em>.</h1><p className="lede">One of KC's fastest-growing suburbs. We work with Lee's Summit small businesses across the historic downtown LS district, the Summit Fair corridor, and the home-services boom serving the new construction east of 470.</p><div className="actions"><a className="btn btn--primary" href="/contact/">Book a 20-min call <span className="arrow">→</span></a><a className="btn btn--ghost" href="/services/">See services</a></div></div></header>
<section className="section"><div className="wrap"><div className="prose" style={{maxWidth: '72ch'}}><h2 style={{marginTop: '0'}}>Lee's Summit is in a small-business growth spurt.</h2><p>Lee's Summit added more new businesses per capita than almost any KC suburb in the past three years. The historic downtown district along 3rd Street is dense with independent retail and restaurants. The corridor around Summit Fair has anchored a new generation of professional services. East of 470, residential construction has pulled in a wave of HVAC, plumbing, landscape, and remodeling shops chasing the new-home market.</p><p>What we see in LS audits: lots of one-owner businesses, growing fast, still running on systems they set up when they had 2 employees. The owner is everywhere, doing everything, and the cracks are showing. <strong>The classic LS automation engagement</strong> is one home-services owner, 3–6 employees, struggling with after-hours calls and quote follow-up.</p><p>We are in Lee's Summit weekly. If you are in the area and want a no-pressure conversation, our calendar is open.</p></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common in Lee's Summit</span><h2 style={{marginTop: '14px'}}>Industries we serve here.</h2></div></div><div className="card-grid"><a className="card" href="/industries/hvac-plumbing-automation-kansas-city/"><span className="tag">Trades</span><h3>HVAC, plumbing & home services</h3><p>Missed-call text-back, quote follow-up, review automation.</p><span className="more">Explore →</span></a><a className="card" href="/industries/restaurant-automation-kansas-city/"><span className="tag">Hospitality</span><h3>Restaurants & food service</h3><p>No-show reduction, review responses, social scheduling.</p><span className="more">Explore →</span></a><a className="card" href="/industries/real-estate-automation-kansas-city/"><span className="tag">Property</span><h3>Real estate agents & brokers</h3><p>5-min lead response, nurture sequences, cold-lead resurrection.</p><span className="more">Explore →</span></a><a className="card" href="/industries/salon-spa-automation-kansas-city/"><span className="tag">Beauty</span><h3>Salons, spas & personal care</h3><p>Online booking, no-show reduction, social posts.</p><span className="more">Explore →</span></a><a className="card" href="/industries/medical-dental-automation-kansas-city/"><span className="tag">Health</span><h3>Medical, dental & clinics</h3><p>Appointment reminders, patient intake, review collection.</p><span className="more">Explore →</span></a><a className="card" href="/industries/law-firm-automation-kansas-city/"><span className="tag">Professional</span><h3>Law firms & accounting</h3><p>Intake, document follow-up, billing reminders.</p><span className="more">Explore →</span></a></div></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="label">How we work</span><h2 style={{marginTop: '14px'}}>The same in Lee's Summit as everywhere.</h2></div></div><div className="card-grid card-grid--2"><div className="card"><span className="tag">Step 01</span><h3>$397 audit</h3><p>2–3 hours in your business. Ranked, written plan of every leak. Yours whether you DIY, hire us to teach you, or hire us to build it.</p></div><div className="card"><span className="tag">Step 02 (optional)</span><h3>Teach or Build</h3><p>You pick. Side-by-side training to run it yourself, or a fixed-bid done-for-you build starting at $500.</p></div></div></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Find your <em>leaks</em>, Lee's Summit.</h2><p className="sub">We drive to your business — same day for emergencies, this week for the rest. Lee's Summit is a ~35 minute drive from our base.</p><div className="actions"><a className="btn btn--invert" href="/contact/">Book a call <span className="arrow">→</span></a><a className="btn btn--ghost-invert" href="/services/system-audit-kansas-city/">Or book the audit</a></div></div></section>
    </main>
  );
}