export const metadata = {
  title: 'AI Automation in Lenexa | Small Business Consulting | S.Y.S.T.E.M. KC',
  description: 'Local AI automation consulting for Lenexa small businesses. In-person audits, fixed-bid builds, monthly retainers that cover your subscriptions. Plain English, no long-term contracts.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">·</span><a href="/">Locations</a><span className="sep">·</span><span className="here">Lenexa</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">Service area · Johnson County, KS</span><h1>AI automation consulting in <em>Lenexa</em>.</h1><p className="lede">City Center Lenexa, the business parks along 95th, and the growing retail and logistics community along I-35. We work with the small and mid-sized businesses that fill them.</p><div className="actions"><a className="btn btn--primary" href="/contact/">Book a 20-min call <span className="arrow">→</span></a><a className="btn btn--ghost" href="/services/">See services</a></div></div></header>
<section className="section"><div className="wrap"><div className="prose" style={{maxWidth: '72ch'}}><h2 style={{marginTop: '0'}}>Lenexa is the quiet operator of the metro.</h2><p>City Center Lenexa has anchored a wave of new development — restaurants, professional services, retail — that did not exist a decade ago. The business parks along 95th have a thick concentration of logistics, light manufacturing, and B2B services. Most of those companies have 5–30 employees and run on a quiet, owner-operator culture.</p><p>What we have learned auditing Lenexa businesses: the leaks are not glamorous. <strong>It is invoice follow-up that has not been touched in 60 days, scheduling that lives in a shared Google calendar with no SOPs, and customer follow-up that happens "when we get a chance."</strong> The fixes are unsexy and high-ROI: automated billing reminders, structured scheduling, real customer comms.</p><p>If you are running a 5–30 person business in Lenexa, you probably do not need a sweeping reinvention. You need the four or five small systems that make the day-to-day not feel like firefighting. That is exactly what an audit identifies and a build delivers.</p></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common in Lenexa</span><h2 style={{marginTop: '14px'}}>Industries we serve here.</h2></div></div><div className="card-grid"><a className="card" href="/industries/hvac-plumbing-automation-kansas-city/"><span className="tag">Trades</span><h3>HVAC, plumbing & home services</h3><p>Missed-call text-back, quote follow-up, review automation.</p><span className="more">Explore →</span></a><a className="card" href="/industries/law-firm-automation-kansas-city/"><span className="tag">Professional</span><h3>Law firms & accounting</h3><p>Intake, document follow-up, billing reminders.</p><span className="more">Explore →</span></a><a className="card" href="/industries/salon-spa-automation-kansas-city/"><span className="tag">Beauty</span><h3>Salons, spas & personal care</h3><p>Online booking, no-show reduction, social posts.</p><span className="more">Explore →</span></a><a className="card" href="/industries/restaurant-automation-kansas-city/"><span className="tag">Hospitality</span><h3>Restaurants & food service</h3><p>No-show reduction, review responses, social scheduling.</p><span className="more">Explore →</span></a><a className="card" href="/industries/real-estate-automation-kansas-city/"><span className="tag">Property</span><h3>Real estate agents & brokers</h3><p>5-min lead response, nurture sequences, cold-lead resurrection.</p><span className="more">Explore →</span></a><a className="card" href="/industries/medical-dental-automation-kansas-city/"><span className="tag">Health</span><h3>Medical, dental & clinics</h3><p>Appointment reminders, patient intake, review collection.</p><span className="more">Explore →</span></a></div></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="label">How we work</span><h2 style={{marginTop: '14px'}}>The same in Lenexa as everywhere.</h2></div></div><div className="card-grid card-grid--2"><div className="card"><span className="tag">Step 01</span><h3>$397 audit</h3><p>2–3 hours in your business. Ranked, written plan of every leak. Yours whether you DIY, hire us to teach you, or hire us to build it.</p></div><div className="card"><span className="tag">Step 02 (optional)</span><h3>Teach or Build</h3><p>You pick. Side-by-side training to run it yourself, or a fixed-bid done-for-you build starting at $500.</p></div></div></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Find your <em>leaks</em>, Lenexa.</h2><p className="sub">We drive to your business — same day for emergencies, this week for the rest. Lenexa is a ~25 minute drive from our base.</p><div className="actions"><a className="btn btn--invert" href="/contact/">Book a call <span className="arrow">→</span></a><a className="btn btn--ghost-invert" href="/services/system-audit-kansas-city/">Or book the audit</a></div></div></section>
    </main>
  );
}