export const metadata = {
  title: 'AI Automation in Topeka | Small Business Consulting | S.Y.S.T.E.M. KC',
  description: 'Local AI automation consulting for Topeka small businesses. In-person audits, fixed-bid builds, monthly retainers that cover your subscriptions.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">·</span><a href="/">Locations</a><span className="sep">·</span><span className="here">Topeka</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">Service area · Shawnee County, KS</span><h1>AI automation consulting in <em>Topeka</em>.</h1><p className="lede">The Kansas capital city is an hour west of Kansas City. We serve Topeka small businesses across the downtown core, the SW Topeka corridor, and the residential growth on the city's west side.</p><div className="actions"><a className="btn btn--primary" href="/contact/">Book a 20-min call <span className="arrow">→</span></a><a className="btn btn--ghost" href="/services/">See services</a></div></div></header>
<section className="section"><div className="wrap"><div className="prose" style={{maxWidth: '72ch'}}><h2 style={{marginTop: '0'}}>Topeka has the capital-city economy.</h2><p>Topeka's economy is anchored by state government, Stormont Vail Health, Washburn University, and a dense small-business community that has been there for generations. Downtown Topeka has been in a slow, real revival — restaurants, retail, and creative businesses are opening in spaces that sat empty 15 years ago.</p><p>Our Topeka audits tend to find: <strong>legacy systems</strong>. Businesses that have run successfully for 20 years on a setup that has not been touched since 2008. The opportunities are big and the change-management is the hardest part — you do not rip out what is working, you augment around it.</p><p>If you are a Topeka business considering automation for the first time, that is almost an advantage. Start with the audit — $397, in-person, 2–3 hours — and you walk away with a plan and zero pressure to do anything with it.</p></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common in Topeka</span><h2 style={{marginTop: '14px'}}>Industries we serve here.</h2></div></div><div className="card-grid"><a className="card" href="/industries/hvac-plumbing-automation-kansas-city/"><span className="tag">Trades</span><h3>HVAC, plumbing & home services</h3><p>Missed-call text-back, quote follow-up, review automation.</p><span className="more">Explore →</span></a><a className="card" href="/industries/law-firm-automation-kansas-city/"><span className="tag">Professional</span><h3>Law firms & accounting</h3><p>Intake, document follow-up, billing reminders.</p><span className="more">Explore →</span></a><a className="card" href="/industries/medical-dental-automation-kansas-city/"><span className="tag">Health</span><h3>Medical, dental & clinics</h3><p>Appointment reminders, patient intake, review collection.</p><span className="more">Explore →</span></a><a className="card" href="/industries/real-estate-automation-kansas-city/"><span className="tag">Property</span><h3>Real estate agents & brokers</h3><p>5-min lead response, nurture sequences, cold-lead resurrection.</p><span className="more">Explore →</span></a><a className="card" href="/industries/salon-spa-automation-kansas-city/"><span className="tag">Beauty</span><h3>Salons, spas & personal care</h3><p>Online booking, no-show reduction, social posts.</p><span className="more">Explore →</span></a><a className="card" href="/industries/restaurant-automation-kansas-city/"><span className="tag">Hospitality</span><h3>Restaurants & food service</h3><p>No-show reduction, review responses, social scheduling.</p><span className="more">Explore →</span></a></div></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Find your <em>leaks</em>, Topeka.</h2><p className="sub">Topeka is a ~1 hour drive from our KC base. We are in Topeka on a weekly basis.</p><div className="actions"><a className="btn btn--invert" href="/contact/">Book a call <span className="arrow">→</span></a></div></div></section>
    </main>
  );
}