export const metadata = {
  title: 'AI Automation in Blue Springs & Independence | Small Business Consulting | S.Y.S.T.E.M. KC',
  description: 'Local AI automation consulting for Blue Springs & Independence small businesses. In-person audits, fixed-bid builds, monthly retainers that cover your subscriptions. Plain English, no long-term contracts.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">·</span><a href="/">Locations</a><span className="sep">·</span><span className="here">Blue Springs & Independence</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">Service area · Eastern Jackson County, MO</span><h1>AI automation consulting in <em>Blue Springs & Independence</em>.</h1><p className="lede">The eastern KC suburbs anchor a deep small-business community — medical, retail, home services, and the local restaurants and salons serving a large working population.</p><div className="actions"><a className="btn btn--primary" href="/contact/">Book a 20-min call <span className="arrow">→</span></a><a className="btn btn--ghost" href="/services/">See services</a></div></div></header>
<section className="section"><div className="wrap"><div className="prose" style={{maxWidth: '72ch'}}><h2 style={{marginTop: '0'}}>East KC is underserved by tech consultants — and benefits the most from a real one.</h2><p>Blue Springs and Independence — running east along I-70 — are home to a working-class small-business community that has not been the target of much "automation" pitching. <strong>That makes us either skeptics or first-movers, depending on the owner.</strong> The medical corridor around Independence Regional, the retail along 39th, and the home-services community spread across both cities are full of businesses that have never been audited by anyone.</p><p>What we tell East KC owners up front: this is not enterprise software. We are not selling you a $50k SaaS rollout. <strong>It is a $397 audit and, if it makes sense, $500–$2,500 in setup work plus a $450/mo retainer that bundles the underlying subscriptions.</strong> Cheaper than the part-time office help most owners are wishing they had.</p><p>If you are a Blue Springs or Independence owner and you are tired of the same conversations about chasing leads, missing calls, and never having time for the office work — we should talk. We drive east on I-70 weekly.</p></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common in Blue Springs & Independence</span><h2 style={{marginTop: '14px'}}>Industries we serve here.</h2></div></div><div className="card-grid"><a className="card" href="/industries/hvac-plumbing-automation-kansas-city/"><span className="tag">Trades</span><h3>HVAC, plumbing & home services</h3><p>Missed-call text-back, quote follow-up, review automation.</p><span className="more">Explore →</span></a><a className="card" href="/industries/medical-dental-automation-kansas-city/"><span className="tag">Health</span><h3>Medical, dental & clinics</h3><p>Appointment reminders, patient intake, review collection.</p><span className="more">Explore →</span></a><a className="card" href="/industries/restaurant-automation-kansas-city/"><span className="tag">Hospitality</span><h3>Restaurants & food service</h3><p>No-show reduction, review responses, social scheduling.</p><span className="more">Explore →</span></a><a className="card" href="/industries/salon-spa-automation-kansas-city/"><span className="tag">Beauty</span><h3>Salons, spas & personal care</h3><p>Online booking, no-show reduction, social posts.</p><span className="more">Explore →</span></a><a className="card" href="/industries/law-firm-automation-kansas-city/"><span className="tag">Professional</span><h3>Law firms & accounting</h3><p>Intake, document follow-up, billing reminders.</p><span className="more">Explore →</span></a><a className="card" href="/industries/real-estate-automation-kansas-city/"><span className="tag">Property</span><h3>Real estate agents & brokers</h3><p>5-min lead response, nurture sequences, cold-lead resurrection.</p><span className="more">Explore →</span></a></div></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="label">How we work</span><h2 style={{marginTop: '14px'}}>The same in Blue Springs & Independence as everywhere.</h2></div></div><div className="card-grid card-grid--2"><div className="card"><span className="tag">Step 01</span><h3>$397 audit</h3><p>2–3 hours in your business. Ranked, written plan of every leak. Yours whether you DIY, hire us to teach you, or hire us to build it.</p></div><div className="card"><span className="tag">Step 02 (optional)</span><h3>Teach or Build</h3><p>You pick. Side-by-side training to run it yourself, or a fixed-bid done-for-you build starting at $500.</p></div></div></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Find your <em>leaks</em>, Blue Springs & Independence.</h2><p className="sub">We drive to your business — same day for emergencies, this week for the rest. Blue Springs and Independence are a ~30 minute drive from our base.</p><div className="actions"><a className="btn btn--invert" href="/contact/">Book a call <span className="arrow">→</span></a><a className="btn btn--ghost-invert" href="/services/system-audit-kansas-city/">Or book the audit</a></div></div></section>
    </main>
  );
}