import FaqAccordion from '../../components/FaqAccordion';

export const metadata = {
  title: 'Business Automation for Kansas City Restaurants | S.Y.S.T.E.M. KC',
  description: 'No-show reduction, review response, social scheduling and catering follow-up automation for Kansas City restaurants. Built for the operational layer around your POS.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">·</span><a href="/">Industries</a><span className="sep">·</span><span className="here">Restaurants & Food Service</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">For Restaurants & Food Service · Kansas City</span><h1>Business automation for <em>Kansas City</em> restaurants.</h1><p className="lede">KC has one of the most exciting food scenes in the country — and the operators running it are exhausted. We do not build POS systems. We build the operational layer around them: reviews, social, reservations, no-shows, and the constant small fires that eat 10 hours a week off the manager's clock.</p><div className="actions"><a className="btn btn--primary" href="/contact/">Book a 20-min call <span className="arrow">→</span></a><a className="btn btn--ghost" href="#automations">See what we build</a></div></div></header>
<section className="section"><div className="wrap"><div className="prose" style={{maxWidth: '72ch'}}><h2 style={{marginTop: '0'}}>You are running the hardest business there is.</h2><p>Restaurant margins are measured in minutes. A 30-minute open table at 7pm Saturday is the difference between a great night and a meh one. A negative review that sits without a response for 48 hours becomes the top result when someone Googles you on Sunday morning.</p><p>Most restaurant tech is built for the chef and the server — POS, KDS, inventory. Almost none of it handles the customer side. That is where the leaks are: <strong>no-shows costing $200–$400 per reserved table</strong>, reviews going unanswered, the social account that nobody has time to post to, the loyalty program that nobody enrolls anyone in.</p><p>We build the calm layer around all of that, so the manager can focus on actually running the night.</p></div></div></section>
<section className="section section--alt" id="automations"><div className="wrap"><div className="section-head"><div><span className="label">What we build for restaurant</span><h2 style={{marginTop: '14px'}}>Built for independent restaurants and small groups.</h2></div></div><div className="card-grid"><div className="card"><span className="tag">01 · Reservations</span><h3>No-show reduction sequence</h3><p>Reservation made → SMS confirmation → reminder 24h before → final confirm 2h before. KC restaurants typically see no-shows drop 30–50% in the first 60 days.</p></div><div className="card"><span className="tag">02 · Reviews</span><h3>Review response automation</h3><p>New Google review? AI drafts a thoughtful, on-brand response. Manager approves with one tap. Negative reviews escalate to you instantly — you respond, others see you care.</p></div><div className="card"><span className="tag">03 · Social</span><h3>Social media scheduling</h3><p>A week of posts batched in 30 minutes — specials, behind-the-scenes, staff highlights. AI drafts captions in your voice; you approve.</p></div><div className="card"><span className="tag">04 · Loyalty</span><h3>Birthday + return-visit triggers</h3><p>Customer birthday in 7 days? They get a "come celebrate" message with a small offer. Have not visited in 60 days? Gentle "we miss you" with a low-pressure incentive.</p></div><div className="card"><span className="tag">05 · Catering</span><h3>Catering inquiry follow-up</h3><p>Catering inquiries are gold. Automated quote-to-close sequence handles the back-and-forth so nothing slips while you are running service.</p></div><div className="card"><span className="tag">06 · Hiring</span><h3>Application screening</h3><p>Resumes come in via Indeed → automated screening text → interview booked. Stops you from missing good hires during dinner rush.</p></div></div></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="label">A day in the life</span><h2 style={{marginTop: '14px'}}>A 40-seat KC restaurant, after 60 days.</h2></div></div><div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '48px'}}><div><h3 style={{fontFamily: 'var(--mono)', fontSize: '13px', letterSpacing: '.12em', color: '#D4322E', textTransform: 'uppercase', fontWeight: '700'}}>Before</h3><ul style={{marginLeft: '18px', color: 'var(--text)', fontSize: '17px', lineHeight: '1.7'}}><li>4 no-shows on a Saturday. ~$1,200 lost.</li><li>One-star review hits at 11am Sunday. Nobody responds till Tuesday.</li><li>Instagram has not been posted to in 3 weeks.</li><li>Manager closes at midnight, opens at 9am.</li></ul></div><div><h3 style={{fontFamily: 'var(--mono)', fontSize: '13px', letterSpacing: '.12em', color: '#1F8A99', textTransform: 'uppercase', fontWeight: '700'}}>After</h3><ul style={{marginLeft: '18px', color: 'var(--text)', fontSize: '17px', lineHeight: '1.7'}}><li>No-show rate down to ~5%. Saturday packed.</li><li>Reviews answered within 90 min — staff sees it, customers feel heard.</li><li>3 posts/week, scheduled in 30 min on Monday morning.</li><li>Manager done at 11pm. Owner finally takes a Tuesday off.</li></ul></div></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common questions</span><h2 style={{marginTop: '14px'}}>From restaurant owners.</h2></div></div><FaqAccordion><div className="faq-item open"><button className="faq-q"><span className="qnum">Q.01</span><span className="qtxt">Do you integrate with my POS or reservation system?</span><span className="qicn">+</span></button><div className="faq-a">We work with the major ones — Toast, Square, Resy, OpenTable, SevenRooms, and others. If yours has any kind of integration hook, we can make it talk to the rest of your stack.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.02</span><span className="qtxt">Will the AI sound like us?</span><span className="qicn">+</span></button><div className="faq-a">Yes. We spend an hour with you up front getting the voice right. Every drafted response is yours to approve before sending — until you trust it enough to let it auto-send.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.03</span><span className="qtxt">What about staff buy-in?</span><span className="qicn">+</span></button><div className="faq-a">A common worry. We deliberately build automations that make staff lives easier (less manager nagging, fewer tedious tasks) so adoption is voluntary.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.04</span><span className="qtxt">Pricing?</span><span className="qicn">+</span></button><div className="faq-a">Most KC restaurants land in a $500–$2,500 build plus a $450–$700/mo retainer. The retainer covers your subscription costs.</div></div></FaqAccordion></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Reclaim your <em>Tuesday off</em>.</h2><p className="sub">$397 in-person audit. We come to your restaurant, find the 3 biggest leaks, and you walk away with a ranked plan. Yours whether you hire us to build it or not.</p><div className="actions"><a className="btn btn--invert" href="/contact/">Book the audit <span className="arrow">→</span></a></div></div></section>
    </main>
  );
}