export const metadata = {
  title: 'AI Automation in St. Joseph | Small Business Consulting | S.Y.S.T.E.M. KC',
  description: 'Local AI automation consulting for St. Joseph small businesses. In-person audits, fixed-bid builds, monthly retainers that cover your subscriptions.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">·</span><a href="/">Locations</a><span className="sep">·</span><span className="here">St. Joseph</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">Service area · Buchanan County, MO</span><h1>AI automation consulting in <em>St. Joseph</em>.</h1><p className="lede">An hour north of Kansas City along I-29. St. Joseph small businesses anchor a regional economy serving northwest Missouri and northeast Kansas — and most of them have never been pitched on real automation work.</p><div className="actions"><a className="btn btn--primary" href="/contact/">Book a 20-min call <span className="arrow">→</span></a><a className="btn btn--ghost" href="/services/">See services</a></div></div></header>
<section className="section"><div className="wrap"><div className="prose" style={{maxWidth: '72ch'}}><h2 style={{marginTop: '0'}}>St. Joseph is the regional service hub north of KC.</h2><p>St. Joseph sits at the center of a regional service economy — northwest Missouri, southeast Nebraska, and northeast Kansas all funnel through. Mosaic Life Care anchors a substantial healthcare community. The historic downtown along Felix Street has seen real revival. The home-services community spans a wider geographic radius than the KC metro suburbs.</p><p>What we tell St. Joe owners: <strong>your customers have higher tolerance for "I will get back to you tomorrow" than a JOCO customer does — but that gap is closing fast.</strong> The businesses installing real automation now are going to look meaningfully more professional than their peers within 12 months, and that translates to market share.</p><p>We drive to St. Joe regularly. Audit is the same $397 whether you are in OP or in St. Joseph. The driving time is on us.</p></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common in St. Joseph</span><h2 style={{marginTop: '14px'}}>Industries we serve here.</h2></div></div><div className="card-grid"><a className="card" href="/industries/hvac-plumbing-automation-kansas-city/"><span className="tag">Trades</span><h3>HVAC, plumbing & home services</h3><p>Missed-call text-back, quote follow-up, review automation.</p><span className="more">Explore →</span></a><a className="card" href="/industries/medical-dental-automation-kansas-city/"><span className="tag">Health</span><h3>Medical, dental & clinics</h3><p>Appointment reminders, patient intake, review collection.</p><span className="more">Explore →</span></a><a className="card" href="/industries/real-estate-automation-kansas-city/"><span className="tag">Property</span><h3>Real estate agents & brokers</h3><p>5-min lead response, nurture sequences, cold-lead resurrection.</p><span className="more">Explore →</span></a><a className="card" href="/industries/restaurant-automation-kansas-city/"><span className="tag">Hospitality</span><h3>Restaurants & food service</h3><p>No-show reduction, review responses, social scheduling.</p><span className="more">Explore →</span></a><a className="card" href="/industries/law-firm-automation-kansas-city/"><span className="tag">Professional</span><h3>Law firms & accounting</h3><p>Intake, document follow-up, billing reminders.</p><span className="more">Explore →</span></a><a className="card" href="/industries/salon-spa-automation-kansas-city/"><span className="tag">Beauty</span><h3>Salons, spas & personal care</h3><p>Online booking, no-show reduction, social posts.</p><span className="more">Explore →</span></a></div></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Find your <em>leaks</em>, St. Joseph.</h2><p className="sub">St. Joseph is a ~1 hour drive from our KC base. We make the trip regularly.</p><div className="actions"><a className="btn btn--invert" href="/contact/">Book a call <span className="arrow">→</span></a></div></div></section>
    </main>
  );
}