export const metadata = {
  title: 'Locations | Kansas City Region Automation Service Area | S.Y.S.T.E.M. KC',
  description: 'In-person automation consulting across the Kansas City region: OP, Lee\\u2019s Summit, Olathe, Lenexa, Northland, Blue Springs, Shawnee, Crossroads, Topeka, St. Joseph, Warrensburg.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">·</span><span className="here">Locations</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">Where we work</span><h1>Kansas City and the <em>whole region</em>.</h1><p className="lede">In-person audits anywhere within a 1- to 1.5-hour drive of downtown KC. The full metro, plus Topeka, St. Joseph, Warrensburg, Lawrence, and the towns between. Every page below has city-specific notes — what we have seen, who we have worked with, and what the local business landscape looks like.</p></div></header>
<section className="section"><div className="wrap"><div className="card-grid"><a className="card" href="/locations/overland-park/"><span className="tag">Johnson County, KS</span><h3>Overland Park</h3><p>Kansas City's largest suburb — and the metro's most concentrated decision-maker base. We work with Overland Park small businesses across the…</p><span className="more">Visit page →</span></a><a className="card" href="/locations/lees-summit/"><span className="tag">Eastern Jackson County, MO</span><h3>Lee's Summit</h3><p>One of KC's fastest-growing suburbs. We work with Lee's Summit small businesses across the historic downtown LS district, the Summit Fair co…</p><span className="more">Visit page →</span></a><a className="card" href="/locations/olathe/"><span className="tag">Johnson County, KS</span><h3>Olathe</h3><p>Johnson County's fastest-growing city. Olathe businesses range from established trades shops near Santa Fe Trail to fresh-out-the-box servic…</p><span className="more">Visit page →</span></a><a className="card" href="/locations/lenexa/"><span className="tag">Johnson County, KS</span><h3>Lenexa</h3><p>City Center Lenexa, the business parks along 95th, and the growing retail and logistics community along I-35. We work with the small and mid…</p><span className="more">Visit page →</span></a><a className="card" href="/locations/northland-kansas-city/"><span className="tag">Clay & Platte Counties, MO</span><h3>Northland Kansas City</h3><p>Liberty, Gladstone, Parkville, Kearney, Smithville. The Northland is residential growth country — and that means a home-services boom and th…</p><span className="more">Visit page →</span></a><a className="card" href="/locations/blue-springs-independence/"><span className="tag">Eastern Jackson County, MO</span><h3>Blue Springs & Independence</h3><p>The eastern KC suburbs anchor a deep small-business community — medical, retail, home services, and the local restaurants and salons serving…</p><span className="more">Visit page →</span></a><a className="card" href="/locations/shawnee-prairie-village/"><span className="tag">Johnson County, KS</span><h3>Shawnee & Prairie Village</h3><p>Two of JOCO's most affluent communities. We work with the boutiques, restaurants, professional firms, and medical practices serving a client…</p><span className="more">Visit page →</span></a><a className="card" href="/locations/downtown-kansas-city/"><span className="tag">Jackson County, MO</span><h3>Downtown KC & Crossroads</h3><p>Crossroads Arts District, Westport, Power & Light, and the creative + tech cluster downtown. We work with the agencies, restaurants, startup…</p><span className="more">Visit page →</span></a></div></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Not on the list?</h2><p className="sub">If you are inside a 90-minute drive of Kansas City, you are inside our service area — even if your city does not have its own page yet. Just ask.</p><div className="actions"><a className="btn btn--invert" href="/contact/">Ask on a free call <span className="arrow">→</span></a></div></div></section>
    </main>
  );
}