export const metadata = {
  title: 'AI Automation in Northland Kansas City | Small Business Consulting | S.Y.S.T.E.M. KC',
  description: 'Local AI automation consulting for Northland Kansas City small businesses. In-person audits, fixed-bid builds, monthly retainers that cover your subscriptions. Plain English, no long-term contracts.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">·</span><a href="/">Locations</a><span className="sep">·</span><span className="here">Northland Kansas City</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">Service area · Clay & Platte Counties, MO</span><h1>AI automation consulting in <em>Northland Kansas City</em>.</h1><p className="lede">Liberty, Gladstone, Parkville, Kearney, Smithville. The Northland is residential growth country — and that means a home-services boom and the local retail and restaurants growing alongside it.</p><div className="actions"><a className="btn btn--primary" href="/contact/">Book a 20-min call <span className="arrow">→</span></a><a className="btn btn--ghost" href="/services/">See services</a></div></div></header>
<section className="section"><div className="wrap"><div className="prose" style={{maxWidth: '72ch'}}><h2 style={{marginTop: '0'}}>The Northland is trades country.</h2><p>Northland Kansas City — covering Liberty, Gladstone, Parkville, Kearney, and Smithville — has been growing residentially for a decade. New subdivisions need HVAC, plumbing, roofing, landscaping, and home-remodeling services. The corridor along North Oak through Gladstone and the downtown areas of Liberty and Parkville are dense with the restaurants, salons, and retail filling out the local economy.</p><p>Our experience auditing Northland trades businesses: <strong>missed-call rate is the killer.</strong> Crews are spread across three or four counties on any given day. The phone rings from a Liberty homeowner with a clogged drain at 11am and goes to voicemail. By the time anyone calls back at 4pm, the homeowner has Googled "plumber near me" and someone in Independence already has the job.</p><p>Missed-call text-back alone typically recovers $5,000–$15,000/month of revenue for a 3–8 truck Northland trades business. It costs $39/mo to run. The math is not subtle.</p></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common in Northland Kansas City</span><h2 style={{marginTop: '14px'}}>Industries we serve here.</h2></div></div><div className="card-grid"><a className="card" href="/industries/hvac-plumbing-automation-kansas-city/"><span className="tag">Trades</span><h3>HVAC, plumbing & home services</h3><p>Missed-call text-back, quote follow-up, review automation.</p><span className="more">Explore →</span></a><a className="card" href="/industries/restaurant-automation-kansas-city/"><span className="tag">Hospitality</span><h3>Restaurants & food service</h3><p>No-show reduction, review responses, social scheduling.</p><span className="more">Explore →</span></a><a className="card" href="/industries/salon-spa-automation-kansas-city/"><span className="tag">Beauty</span><h3>Salons, spas & personal care</h3><p>Online booking, no-show reduction, social posts.</p><span className="more">Explore →</span></a><a className="card" href="/industries/real-estate-automation-kansas-city/"><span className="tag">Property</span><h3>Real estate agents & brokers</h3><p>5-min lead response, nurture sequences, cold-lead resurrection.</p><span className="more">Explore →</span></a><a className="card" href="/industries/medical-dental-automation-kansas-city/"><span className="tag">Health</span><h3>Medical, dental & clinics</h3><p>Appointment reminders, patient intake, review collection.</p><span className="more">Explore →</span></a><a className="card" href="/industries/law-firm-automation-kansas-city/"><span className="tag">Professional</span><h3>Law firms & accounting</h3><p>Intake, document follow-up, billing reminders.</p><span className="more">Explore →</span></a></div></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="label">How we work</span><h2 style={{marginTop: '14px'}}>The same in Northland Kansas City as everywhere.</h2></div></div><div className="card-grid card-grid--2"><div className="card"><span className="tag">Step 01</span><h3>$397 audit</h3><p>2–3 hours in your business. Ranked, written plan of every leak. Yours whether you DIY, hire us to teach you, or hire us to build it.</p></div><div className="card"><span className="tag">Step 02 (optional)</span><h3>Teach or Build</h3><p>You pick. Side-by-side training to run it yourself, or a fixed-bid done-for-you build starting at $500.</p></div></div></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Find your <em>leaks</em>, Northland Kansas City.</h2><p className="sub">We drive to your business — same day for emergencies, this week for the rest. The Northland is a ~20 minute drive from our base.</p><div className="actions"><a className="btn btn--invert" href="/contact/">Book a call <span className="arrow">→</span></a><a className="btn btn--ghost-invert" href="/services/system-audit-kansas-city/">Or book the audit</a></div></div></section>
    </main>
  );
}