export const metadata = {
  title: 'AI Automation in Warrensburg | Small Business Consulting | S.Y.S.T.E.M. KC',
  description: 'Local AI automation consulting for Warrensburg small businesses. In-person audits, fixed-bid builds, monthly retainers that cover your subscriptions.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">·</span><a href="/">Locations</a><span className="sep">·</span><span className="here">Warrensburg</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">Service area · Johnson County, MO</span><h1>AI automation consulting in <em>Warrensburg</em>.</h1><p className="lede">An hour southeast of Kansas City. Warrensburg anchors a college town and regional service economy around UCM and Whiteman Air Force Base. We work with the trades, professional, and retail businesses that serve this distinctive market.</p><div className="actions"><a className="btn btn--primary" href="/contact/">Book a 20-min call <span className="arrow">→</span></a><a className="btn btn--ghost" href="/services/">See services</a></div></div></header>
<section className="section"><div className="wrap"><div className="prose" style={{maxWidth: '72ch'}}><h2 style={{marginTop: '0'}}>Warrensburg has a uniquely transient customer base.</h2><p>Warrensburg is shaped by two large institutions: the University of Central Missouri and Whiteman Air Force Base. That means a customer base that turns over substantially every few years — students cycling through, military families rotating in and out, civilian staff that follows both.</p><p>For local businesses, this creates a specific operational challenge: <strong>you cannot rely on customers remembering you from last time.</strong> Every season is a new cohort. Reviews matter exponentially more here than in a stable suburban market — they are how a new arrival decides who to call.</p><p>Automation work in Warrensburg leans hard into review velocity, fast and welcoming first-time-customer experiences, and tight follow-up sequences that prevent first-visit-only patterns. We have audited and worked with Warrensburg trades and professional services. The drive is worth it.</p></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common in Warrensburg</span><h2 style={{marginTop: '14px'}}>Industries we serve here.</h2></div></div><div className="card-grid"><a className="card" href="/industries/hvac-plumbing-automation-kansas-city/"><span className="tag">Trades</span><h3>HVAC, plumbing & home services</h3><p>Missed-call text-back, quote follow-up, review automation.</p><span className="more">Explore →</span></a><a className="card" href="/industries/restaurant-automation-kansas-city/"><span className="tag">Hospitality</span><h3>Restaurants & food service</h3><p>No-show reduction, review responses, social scheduling.</p><span className="more">Explore →</span></a><a className="card" href="/industries/medical-dental-automation-kansas-city/"><span className="tag">Health</span><h3>Medical, dental & clinics</h3><p>Appointment reminders, patient intake, review collection.</p><span className="more">Explore →</span></a><a className="card" href="/industries/salon-spa-automation-kansas-city/"><span className="tag">Beauty</span><h3>Salons, spas & personal care</h3><p>Online booking, no-show reduction, social posts.</p><span className="more">Explore →</span></a><a className="card" href="/industries/real-estate-automation-kansas-city/"><span className="tag">Property</span><h3>Real estate agents & brokers</h3><p>5-min lead response, nurture sequences, cold-lead resurrection.</p><span className="more">Explore →</span></a><a className="card" href="/industries/law-firm-automation-kansas-city/"><span className="tag">Professional</span><h3>Law firms & accounting</h3><p>Intake, document follow-up, billing reminders.</p><span className="more">Explore →</span></a></div></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Find your <em>leaks</em>, Warrensburg.</h2><p className="sub">Warrensburg is a ~1 hour drive from our KC base.</p><div className="actions"><a className="btn btn--invert" href="/contact/">Book a call <span className="arrow">→</span></a></div></div></section>
    </main>
  );
}