export const metadata = {
  title: 'AI Automation in Olathe | Small Business Consulting | S.Y.S.T.E.M. KC',
  description: 'Local AI automation consulting for Olathe small businesses. In-person audits, fixed-bid builds, monthly retainers that cover your subscriptions. Plain English, no long-term contracts.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">·</span><a href="/">Locations</a><span className="sep">·</span><span className="here">Olathe</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">Service area · Johnson County, KS</span><h1>AI automation consulting in <em>Olathe</em>.</h1><p className="lede">Johnson County's fastest-growing city. Olathe businesses range from established trades shops near Santa Fe Trail to fresh-out-the-box service companies starting up east of K-7. We work with all of them — manufacturing, healthcare, trades, and the retail filling the new commercial spaces.</p><div className="actions"><a className="btn btn--primary" href="/contact/">Book a 20-min call <span className="arrow">→</span></a><a className="btn btn--ghost" href="/services/">See services</a></div></div></header>
<section className="section"><div className="wrap"><div className="prose" style={{maxWidth: '72ch'}}><h2 style={{marginTop: '0'}}>Olathe is the underserved growth hub of the metro.</h2><p>Olathe is growing faster than the consulting market serving it. Most local owners we meet have never been pitched on automation in any serious way — and they are the businesses that benefit the most. <strong>Earliest-mover advantage is real in a market that has not been saturated</strong>, and Olathe is one of the last KC sub-markets that has not been.</p><p>The business landscape ranges from the older industrial and trades community along Santa Fe Trail Drive to the newer healthcare and professional services along K-7. Olathe's small manufacturers — there are more than people think — share the same operational pain as service businesses: lead capture is slow, follow-up is sticky-note-based, and the owner is doing too much.</p><p>We have audited and built for Olathe HVAC, dental, real estate, and manufacturing-services clients. Patterns: the missed-call text-back recovers 3–5 jobs a week, the no-show reminder cuts the dental schedule loss by half, and the cost is meaningfully lower than a part-time admin hire.</p></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common in Olathe</span><h2 style={{marginTop: '14px'}}>Industries we serve here.</h2></div></div><div className="card-grid"><a className="card" href="/industries/hvac-plumbing-automation-kansas-city/"><span className="tag">Trades</span><h3>HVAC, plumbing & home services</h3><p>Missed-call text-back, quote follow-up, review automation.</p><span className="more">Explore →</span></a><a className="card" href="/industries/medical-dental-automation-kansas-city/"><span className="tag">Health</span><h3>Medical, dental & clinics</h3><p>Appointment reminders, patient intake, review collection.</p><span className="more">Explore →</span></a><a className="card" href="/industries/real-estate-automation-kansas-city/"><span className="tag">Property</span><h3>Real estate agents & brokers</h3><p>5-min lead response, nurture sequences, cold-lead resurrection.</p><span className="more">Explore →</span></a><a className="card" href="/industries/law-firm-automation-kansas-city/"><span className="tag">Professional</span><h3>Law firms & accounting</h3><p>Intake, document follow-up, billing reminders.</p><span className="more">Explore →</span></a><a className="card" href="/industries/restaurant-automation-kansas-city/"><span className="tag">Hospitality</span><h3>Restaurants & food service</h3><p>No-show reduction, review responses, social scheduling.</p><span className="more">Explore →</span></a><a className="card" href="/industries/salon-spa-automation-kansas-city/"><span className="tag">Beauty</span><h3>Salons, spas & personal care</h3><p>Online booking, no-show reduction, social posts.</p><span className="more">Explore →</span></a></div></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="label">How we work</span><h2 style={{marginTop: '14px'}}>The same in Olathe as everywhere.</h2></div></div><div className="card-grid card-grid--2"><div className="card"><span className="tag">Step 01</span><h3>$397 audit</h3><p>2–3 hours in your business. Ranked, written plan of every leak. Yours whether you DIY, hire us to teach you, or hire us to build it.</p></div><div className="card"><span className="tag">Step 02 (optional)</span><h3>Teach or Build</h3><p>You pick. Side-by-side training to run it yourself, or a fixed-bid done-for-you build starting at $500.</p></div></div></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Find your <em>leaks</em>, Olathe.</h2><p className="sub">We drive to your business — same day for emergencies, this week for the rest. Olathe is a ~30 minute drive from our base.</p><div className="actions"><a className="btn btn--invert" href="/contact/">Book a call <span className="arrow">→</span></a><a className="btn btn--ghost-invert" href="/services/system-audit-kansas-city/">Or book the audit</a></div></div></section>
    </main>
  );
}