export const metadata = {
  title: 'AI Automation in Shawnee & Prairie Village | Small Business Consulting | S.Y.S.T.E.M. KC',
  description: 'Local AI automation consulting for Shawnee & Prairie Village small businesses. In-person audits, fixed-bid builds, monthly retainers that cover your subscriptions. Plain English, no long-term contracts.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">·</span><a href="/">Locations</a><span className="sep">·</span><span className="here">Shawnee & Prairie Village</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">Service area · Johnson County, KS</span><h1>AI automation consulting in <em>Shawnee & Prairie Village</em>.</h1><p className="lede">Two of JOCO's most affluent communities. We work with the boutiques, restaurants, professional firms, and medical practices serving a clientele with high expectations and high ability to pay.</p><div className="actions"><a className="btn btn--primary" href="/contact/">Book a 20-min call <span className="arrow">→</span></a><a className="btn btn--ghost" href="/services/">See services</a></div></div></header>
<section className="section"><div className="wrap"><div className="prose" style={{maxWidth: '72ch'}}><h2 style={{marginTop: '0'}}>A clientele that expects polish.</h2><p>Shawnee and Prairie Village have some of the highest household incomes in the metro. <strong>The customers your business serves are used to top-tier digital experiences — Amazon-level booking, instant responses, professional follow-up.</strong> Falling short of that bar in 2026 is more costly here than almost anywhere.</p><p>The Prairie Village shopping district, the downtown Shawnee corridor, and the dense medical and professional cluster around 75th have a different operational profile than blue-collar suburbs. Customers expect to book online at 10pm and hear back by 9am. They are happy to pay a premium for the service — they are <em>not</em> happy to chase you for a quote.</p><p>What we install for Shawnee/PV businesses: <strong>polished, on-brand, frictionless</strong>. Online booking that respects your real availability. Confirmation flows that feel like a concierge. Review requests that go out with a personalized note, not a generic template. The work and the price feel premium because they are.</p></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common in Shawnee & Prairie Village</span><h2 style={{marginTop: '14px'}}>Industries we serve here.</h2></div></div><div className="card-grid"><a className="card" href="/industries/medical-dental-automation-kansas-city/"><span className="tag">Health</span><h3>Medical, dental & clinics</h3><p>Appointment reminders, patient intake, review collection.</p><span className="more">Explore →</span></a><a className="card" href="/industries/salon-spa-automation-kansas-city/"><span className="tag">Beauty</span><h3>Salons, spas & personal care</h3><p>Online booking, no-show reduction, social posts.</p><span className="more">Explore →</span></a><a className="card" href="/industries/law-firm-automation-kansas-city/"><span className="tag">Professional</span><h3>Law firms & accounting</h3><p>Intake, document follow-up, billing reminders.</p><span className="more">Explore →</span></a><a className="card" href="/industries/real-estate-automation-kansas-city/"><span className="tag">Property</span><h3>Real estate agents & brokers</h3><p>5-min lead response, nurture sequences, cold-lead resurrection.</p><span className="more">Explore →</span></a><a className="card" href="/industries/restaurant-automation-kansas-city/"><span className="tag">Hospitality</span><h3>Restaurants & food service</h3><p>No-show reduction, review responses, social scheduling.</p><span className="more">Explore →</span></a><a className="card" href="/industries/hvac-plumbing-automation-kansas-city/"><span className="tag">Trades</span><h3>HVAC, plumbing & home services</h3><p>Missed-call text-back, quote follow-up, review automation.</p><span className="more">Explore →</span></a></div></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="label">How we work</span><h2 style={{marginTop: '14px'}}>The same in Shawnee & Prairie Village as everywhere.</h2></div></div><div className="card-grid card-grid--2"><div className="card"><span className="tag">Step 01</span><h3>$397 audit</h3><p>2–3 hours in your business. Ranked, written plan of every leak. Yours whether you DIY, hire us to teach you, or hire us to build it.</p></div><div className="card"><span className="tag">Step 02 (optional)</span><h3>Teach or Build</h3><p>You pick. Side-by-side training to run it yourself, or a fixed-bid done-for-you build starting at $500.</p></div></div></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Find your <em>leaks</em>, Shawnee & Prairie Village.</h2><p className="sub">We drive to your business — same day for emergencies, this week for the rest. Shawnee and Prairie Village are a ~20 minute drive from our base.</p><div className="actions"><a className="btn btn--invert" href="/contact/">Book a call <span className="arrow">→</span></a><a className="btn btn--ghost-invert" href="/services/system-audit-kansas-city/">Or book the audit</a></div></div></section>
    </main>
  );
}