import FaqAccordion from '../../components/FaqAccordion';

export const metadata = {
  title: 'The 60-Day Profit Challenge for Law Firm Owners | S.Y.S.T.E.M. KC',
  description: 'Live 1-on-1 business growth training for law firm owners. Fix intake, improve client acquisition, recover billable hours, and add $20,000 in new firm revenue in 60 days — guaranteed.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">&middot;</span><a href="/industries/">Industries</a><span className="sep">&middot;</span><span className="here">Law Firms &amp; Professional Services</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">For Law Firms &amp; Professional Services </span><h1>The 60-Day Law Firm $20,000 Profit Challenge</h1><p className="lede">Your attorneys bill at $200&ndash;$450/hr. Every hour spent on intake, follow-up, scheduling, and chasing documents is a billable hour not captured. The 60-Day Profit Challenge teaches law firm owners how to fix the revenue model, fill the intake pipeline, and build a practice that grows without the principal doing all the admin.</p><p className="sub">Add $20,000 in new revenue in 60 days &mdash; or I work for free until you do.</p><div className="actions"><a className="btn btn--primary" href="/apply/">Apply Now &rarr;</a><a className="btn btn--ghost" href="/the-challenge/">See the Challenge</a></div></div></header>
{/* WHO THIS IS FOR + GUARANTEE */}
      <section style={{background: 'var(--bg-green-tint)', padding: '80px 0', borderBottom: '1px solid var(--rule)'}}>
        <div className="wrap">
          <div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '64px', alignItems: 'center'}}>
            <div>
              <p style={{fontFamily: 'var(--mono)', fontSize: '12px', letterSpacing: '.18em', textTransform: 'uppercase', color: 'var(--green)', fontWeight: '700', marginBottom: '20px'}}>Who this is for</p>
              <h2 style={{fontFamily: 'var(--sans)', fontSize: 'clamp(28px, 3.5vw, 46px)', fontWeight: '900', lineHeight: '1.1', letterSpacing: '-.03em', color: 'var(--blue-deep)'}}>Built for attorneys who want to practice law, not chase paperwork.</h2>
              <p style={{marginTop: '24px', fontSize: '18px', lineHeight: '1.75', color: 'var(--muted)'}}>Law firm owners didn&rsquo;t build a practice to spend their billable hours on intake follow-up, document chasing, and aging A/R. Every hour not billed is a real dollar lost. The inefficiency isn&rsquo;t a character flaw &mdash; it&rsquo;s a process gap. The expertise is there. The growth system is missing.</p>
              <p style={{marginTop: '16px', fontFamily: 'var(--serif)', fontStyle: 'italic', fontSize: '22px', color: 'var(--blue-deep)', lineHeight: '1.35'}}>Success at the firm level isn&rsquo;t about billing more hours &mdash; it&rsquo;s about building the intake, retention, and referral system that makes every hour count.</p>
            </div>
            <div style={{background: 'var(--blue-deep)', borderRadius: '20px', padding: '44px 40px', textAlign: 'center'}}>
              <p style={{fontFamily: 'var(--mono)', fontSize: '11px', letterSpacing: '.18em', textTransform: 'uppercase', color: 'var(--green)', fontWeight: '700', marginBottom: '8px'}}>The 60-Day Law Firm Profit Challenge &mdash; Guarantee</p>
              <div style={{fontFamily: 'var(--serif)', fontSize: 'clamp(56px, 8vw, 88px)', fontWeight: '900', lineHeight: '1', color: '#fff', letterSpacing: '-.03em'}}>$20,000</div>
              <p style={{marginTop: '16px', fontSize: '19px', fontWeight: '700', color: '#fff', lineHeight: '1.4'}}>in new revenue in 60 days &mdash; or I work for free until you do.</p>
              <p style={{marginTop: '14px', fontSize: '14px', color: 'rgba(255,255,255,.6)', lineHeight: '1.6'}}>No contracts. No fine print. We build your money model, marketing, sales system, referrals, and operations together &mdash; live and 1-on-1. If it doesn&rsquo;t produce, I keep working at no extra cost.</p>
              <div style={{marginTop: '28px', display: 'flex', flexDirection: 'column', gap: '10px', alignItems: 'center'}}>
                <a className="btn btn--primary" href="/apply/" style={{width: '100%', justifyContent: 'center', fontSize: '17px', padding: '16px 24px'}}>Apply for a free fit call &rarr;</a>
                <a href="/the-challenge/" style={{fontSize: '13px', color: 'rgba(255,255,255,.5)', fontFamily: 'var(--mono)', letterSpacing: '.06em'}}>See everything included in the Challenge &rarr;</a>
              </div>
            </div>
          </div>
        </div>
      </section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Inside the 60-Day Challenge</span><h2 style={{marginTop: '14px'}}>Law firm &amp; professional services growth &mdash; built for law firm owners.</h2></div></div><div className="card-grid"><div className="card"><span className="tag">01 &middot; Practice Positioning</span><h3>Who you are for and why they should hire you</h3><p>Offer clarity, niche definition, practice area positioning. Most small firms win on price by accident. We fix the positioning so you compete on value and close more consultations.</p></div><div className="card"><span className="tag">02 &middot; Client Acquisition</span><h3>More of the right inquiries, from the right places</h3><p>Google Business Profile, legal directories, referral source mapping, local SEO. We build the acquisition system that keeps qualified leads coming in consistently.</p></div><div className="card"><span className="tag">03 &middot; Speed-to-Lead</span><h3>The firm that calls back first gets the retainer</h3><p>Every inquiry answered within hours, not days. Consultation booking flow, intake questions, conflict check sequence &mdash; automated so your attorneys spend time on case work, not gatekeeping.</p></div><div className="card"><span className="tag">04 &middot; Intake &amp; Conversion</span><h3>From inquiry to signed retainer in 48 hours</h3><p>Engagement letter flow, e-sign sequence, retainer collection. We cut the average consult-to-retainer timeline so less revenue walks out the door while the paperwork sits.</p></div><div className="card"><span className="tag">05 &middot; Billing &amp; Client Retention</span><h3>A/R aging is a cash flow problem with a process solution</h3><p>Invoice follow-up sequences, document collection, case-update communications. We build the process that keeps money moving and clients feeling heard.</p></div><div className="card"><span className="tag">06 &middot; Reviews &amp; Referrals</span><h3>Most referrals happen by accident. We make them a system.</h3><p>Post-matter review requests, referral partner outreach, Avvo and Google review velocity. The compounding effect of 30+ reviews cannot be overstated for local search.</p></div></div></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="label">A day in the life</span><h2 style={{marginTop: '14px'}}>A 3-attorney firm, after 90 days.</h2></div></div><div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '48px'}}><div><h3 style={{fontFamily: 'var(--mono)', fontSize: '13px', letterSpacing: '.12em', color: '#D4322E', textTransform: 'uppercase', fontWeight: '700'}}>Before</h3><ul style={{marginLeft: '18px', color: 'var(--text)', fontSize: '17px', lineHeight: '1.7'}}><li>Potential client calls Friday at 3pm. Returned Monday. Already hired someone.</li><li>5 engagement letters waiting on a signature for weeks.</li><li>$23k in 60+ day overdue invoices.</li><li>Junior attorney spends 4 hrs/week on follow-up emails.</li></ul></div><div><h3 style={{fontFamily: 'var(--mono)', fontSize: '13px', letterSpacing: '.12em', color: '#1F8A99', textTransform: 'uppercase', fontWeight: '700'}}>After</h3><ul style={{marginLeft: '18px', color: 'var(--text)', fontSize: '17px', lineHeight: '1.7'}}><li>New inquiry &rarr; consult booked within 2 hours, 24/7.</li><li>Engagement letters auto-sent, signed in 48hr avg.</li><li>A/R aging cleaned up &mdash; system reminds, escalates, flags.</li><li>Junior attorney back on case work. Firm bills 15% more.</li></ul></div></div></div></section>
<section style={{background: 'var(--bg-green-tint)', padding: '80px 0'}}><div className="wrap" style={{display: 'flex', justifyContent: 'center'}}><div style={{maxWidth: '560px', background: 'var(--blue-deep)', borderRadius: '16px', padding: '48px', color: '#fff'}}><span style={{fontFamily: 'var(--mono)', fontSize: '11px', letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--green)', fontWeight: '700', display: 'block', marginBottom: '24px'}}>The 60-Day Profit Challenge &mdash; Guarantee</span><div style={{fontSize: 'clamp(52px, 7vw, 80px)', fontWeight: '900', fontFamily: 'var(--sans)', lineHeight: '1', color: '#fff', letterSpacing: '-.04em', marginBottom: '24px'}}>$20,000</div><p style={{fontSize: '18px', lineHeight: '1.65', marginBottom: '32px', color: 'rgba(255,255,255,0.88)'}}>If you do not add $20,000 in new revenue to your practice within 60 days, I keep working with you &mdash; live, 1-on-1 &mdash; for free until you do. No service credit. No conditions. I work for free until the number is hit.</p><div className="actions"><a className="btn btn--primary" href="/apply/">Apply Now &rarr;</a><a className="btn btn--ghost-invert" href="/the-challenge/">See everything in the Challenge</a></div></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common questions</span><h2 style={{marginTop: '14px'}}>From law-firm owners.</h2></div></div><FaqAccordion><div className="faq-item open"><button className="faq-q"><span className="qnum">Q.01</span><span className="qtxt">What exactly is the 60-Day Profit Challenge?</span><span className="qicn">+</span></button><div className="faq-a">The 60-Day Profit Challenge is a live, 1-on-1 business growth program for law firm owners and managing partners. Over 60 days, we work through your revenue model, client acquisition, intake process, billing systems, and referral engine &mdash; together, in live sessions, built around your specific practice. Not a course. Not a consultant report. Real strategy, real work, real results.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.02</span><span className="qtxt">What does the Challenge focus on for a law firm specifically?</span><span className="qicn">+</span></button><div className="faq-a">For law firms, the Challenge focuses on the highest-leverage moves for a service professional: offer clarity and positioning, intake and consultation-to-retainer conversion, response time and pipeline velocity, A/R and billing processes, and the referral and review engine that compounds over time. We have worked with professional services firms across the country and the playbook is built for how a solo or small-firm practice actually runs.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.03</span><span className="qtxt">Is this a course or a consulting retainer?</span><span className="qicn">+</span></button><div className="faq-a">Neither &mdash; it is a working engagement. We build the actual growth strategy for your practice, install the systems, and stay in live sessions until $20,000 in new revenue is added. You are not watching videos. You are building a real plan with a real operator.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.04</span><span className="qtxt">What is the guarantee, exactly?</span><span className="qicn">+</span></button><div className="faq-a">If you do not add $20,000 in new revenue within 60 days, I keep working with you &mdash; live, 1-on-1 &mdash; for free until you do. No service credit. No conditions. I work for free until the number is hit.</div></div></FaqAccordion></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Ready to add $20,000 in new <em>firm revenue</em>?</h2><p className="sub">Apply to see if your practice qualifies. First conversation is free.</p><div className="actions"><a className="btn btn--invert" href="/apply/">Apply Now &rarr;</a></div></div></section>
    </main>
  );
}
