import FaqAccordion from '../../components/FaqAccordion';

export const metadata = {
  title: 'AI Automation for Kansas City Law Firms & Accounting | S.Y.S.T.E.M. KC',
  description: 'Intake, engagement letter, document follow-up and billing reminder automation for Kansas City law firms. Every hour automated is a billable hour recovered.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">·</span><a href="/">Industries</a><span className="sep">·</span><span className="here">Law Firms & Professional Services</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">For Law Firms & Professional Services · Kansas City</span><h1>AI automation for <em>Kansas City</em> law firms.</h1><p className="lede">Every hour you spend on intake, follow-up, or billing reminders is a billable hour you did not capture. We build the operational systems around the practice — intake, client comms, document follow-up, scheduling — so your attorneys spend time on case work, not on chasing.</p><div className="actions"><a className="btn btn--primary" href="/contact/">Book a 20-min call <span className="arrow">→</span></a><a className="btn btn--ghost" href="#automations">See what we build</a></div></div></header>
<section className="section"><div className="wrap"><div className="prose" style={{maxWidth: '72ch'}}><h2 style={{marginTop: '0'}}>Every hour automated is a billable hour recovered.</h2><p>Lawyers do not have a marketing problem. They have a <strong>time problem</strong>. A solo or small-firm attorney bills out at $200–$450/hr. Every hour spent on intake forms, scheduling, document chasing, and overdue invoice reminders is an hour not billed.</p><p>Worse: most of that work happens reactively. A potential client calls; nobody calls back for two days; they hire someone else. A signed retainer sits because the client never returned the W-9. An overdue invoice ages another 30 days because nobody had time to write the reminder email.</p><p>None of this requires legal judgment. All of it can be handled by systems that respect attorney-client privilege, run within your existing case-management software, and feel professional — not spammy.</p></div></div></section>
<section className="section section--alt" id="automations"><div className="wrap"><div className="section-head"><div><span className="label">What we build for law-firm</span><h2 style={{marginTop: '14px'}}>Built for solo and small-firm practices.</h2></div></div><div className="card-grid"><div className="card"><span className="tag">01 · Intake</span><h3>Conflict-checked intake workflow</h3><p>Inquiry comes in → automated qualifying questions → conflict check against your database → consultation booked. All before an attorney spends a billable minute.</p></div><div className="card"><span className="tag">02 · Engagement</span><h3>Engagement letter + retainer flow</h3><p>Consult complete → engagement letter goes out → e-sign → retainer paid → matter opened. Cuts the average "consult to retainer" timeline by 60%.</p></div><div className="card"><span className="tag">03 · Documents</span><h3>Document collection sequences</h3><p>Client needs to provide 7 documents? Automated reminders at +2 days, +5 days, +10 days, with a checklist of what is still missing. Polite but persistent.</p></div><div className="card"><span className="tag">04 · Billing</span><h3>Invoice follow-up automation</h3><p>Invoice over 30 days? Automated reminder. Over 60? Escalation. Over 90? Flagged to the partner. No more aging A/R because nobody had time.</p></div><div className="card"><span className="tag">05 · Calendar</span><h3>Court-deadline aware scheduling</h3><p>Auto-schedule consults and case meetings around court dates, statutes of limitations, and key deadlines. Reminders fire for clients automatically.</p></div><div className="card"><span className="tag">06 · Marketing</span><h3>Closed-case review request</h3><p>Case closes favorably → automated review request → Avvo, Google, your testimonials page. Compounding ranking benefits in local search.</p></div></div></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="label">A day in the life</span><h2 style={{marginTop: '14px'}}>A 3-attorney KC firm, after 90 days.</h2></div></div><div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '48px'}}><div><h3 style={{fontFamily: 'var(--mono)', fontSize: '13px', letterSpacing: '.12em', color: '#D4322E', textTransform: 'uppercase', fontWeight: '700'}}>Before</h3><ul style={{marginLeft: '18px', color: 'var(--text)', fontSize: '17px', lineHeight: '1.7'}}><li>Potential client calls Friday at 3pm. Returned Monday. Already hired someone.</li><li>5 engagement letters waiting on a signature for weeks.</li><li>$23k in 60+ day overdue invoices.</li><li>Junior attorney spends 4 hrs/week on follow-up emails.</li></ul></div><div><h3 style={{fontFamily: 'var(--mono)', fontSize: '13px', letterSpacing: '.12em', color: '#1F8A99', textTransform: 'uppercase', fontWeight: '700'}}>After</h3><ul style={{marginLeft: '18px', color: 'var(--text)', fontSize: '17px', lineHeight: '1.7'}}><li>New inquiry → consult booked within 2 hours, 24/7.</li><li>Engagement letters auto-sent, signed in 48hr avg.</li><li>A/R aging cleaned up — system reminds, escalates, flags.</li><li>Junior attorney back on case work. Firm bills 15% more.</li></ul></div></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common questions</span><h2 style={{marginTop: '14px'}}>From law-firm owners.</h2></div></div><FaqAccordion><div className="faq-item open"><button className="faq-q"><span className="qnum">Q.01</span><span className="qtxt">Will this work with Clio, MyCase, or PracticePanther?</span><span className="qicn">+</span></button><div className="faq-a">Yes. We integrate alongside your case-management software so you do not duplicate data entry.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.02</span><span className="qtxt">What about attorney-client privilege?</span><span className="qicn">+</span></button><div className="faq-a">We architect everything to respect privilege. Automated communications go out under attorney supervision; nothing AI-generated leaves the system without a human review when matter-sensitive.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.03</span><span className="qtxt">Is this just templated emails?</span><span className="qicn">+</span></button><div className="faq-a">No. The system pulls real case data and references the actual matter. It feels personal because it is using real specifics.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.04</span><span className="qtxt">Pricing?</span><span className="qicn">+</span></button><div className="faq-a">Most solo and small firms land in a $1,500–$5,000 build plus a $450–$1,200/mo retainer that covers software and most AI usage.</div></div></FaqAccordion></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Recover <em>billable hours</em>.</h2><p className="sub">$397 in-person audit. We come to your office, find the 3 biggest leaks, and you walk away with a ranked plan. Yours whether you hire us to build it or not.</p><div className="actions"><a className="btn btn--invert" href="/contact/">Book the audit <span className="arrow">→</span></a></div></div></section>
    </main>
  );
}