export const metadata = {
  title: 'AI Automation in Overland Park | Small Business Consulting | S.Y.S.T.E.M. KC',
  description: 'Local AI automation consulting for Overland Park small businesses. In-person audits, fixed-bid builds, monthly retainers that cover your subscriptions. Plain English, no long-term contracts.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">·</span><a href="/">Locations</a><span className="sep">·</span><span className="here">Overland Park</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">Service area · Johnson County, KS</span><h1>AI automation consulting in <em>Overland Park</em>.</h1><p className="lede">Kansas City's largest suburb — and the metro's most concentrated decision-maker base. We work with Overland Park small businesses across the College Boulevard corridor, downtown OP, and the south Metcalf businesses serving JOCO's professional community.</p><div className="actions"><a className="btn btn--primary" href="/contact/">Book a 20-min call <span className="arrow">→</span></a><a className="btn btn--ghost" href="/services/">See services</a></div></div></header>
<section className="section"><div className="wrap"><div className="prose" style={{maxWidth: '72ch'}}><h2 style={{marginTop: '0'}}>Overland Park is where small business meets big spending power.</h2><p>Overland Park has more household income per square mile than almost anywhere in the metro. The corridor along College Boulevard and Metcalf Avenue, the businesses tucked into downtown OP, and the medical and professional cluster around Menorah and the Sprint campus area all share one thing: <strong>their customers expect a professional experience</strong>.</p><p>"Professional" in 2026 means: responsive when called, easy to book online, smooth digital intake, follow-up that does not feel like crickets. That is exactly where most small businesses fall short — and where small, well-designed automation work moves the needle fastest.</p><p>We have audited businesses across the JOCO professional community — dental practices, real estate teams, medical offices, financial advisors, and trades businesses serving the area's homeowners. The patterns repeat. The fix is usually 30–60 hours of focused setup work and ~$450/mo to run.</p></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common in Overland Park</span><h2 style={{marginTop: '14px'}}>Industries we serve here.</h2></div></div><div className="card-grid"><a className="card" href="/industries/medical-dental-automation-kansas-city/"><span className="tag">Health</span><h3>Medical, dental & clinics</h3><p>Appointment reminders, patient intake, review collection.</p><span className="more">Explore →</span></a><a className="card" href="/industries/law-firm-automation-kansas-city/"><span className="tag">Professional</span><h3>Law firms & accounting</h3><p>Intake, document follow-up, billing reminders.</p><span className="more">Explore →</span></a><a className="card" href="/industries/real-estate-automation-kansas-city/"><span className="tag">Property</span><h3>Real estate agents & brokers</h3><p>5-min lead response, nurture sequences, cold-lead resurrection.</p><span className="more">Explore →</span></a><a className="card" href="/industries/hvac-plumbing-automation-kansas-city/"><span className="tag">Trades</span><h3>HVAC, plumbing & home services</h3><p>Missed-call text-back, quote follow-up, review automation.</p><span className="more">Explore →</span></a><a className="card" href="/industries/salon-spa-automation-kansas-city/"><span className="tag">Beauty</span><h3>Salons, spas & personal care</h3><p>Online booking, no-show reduction, social posts.</p><span className="more">Explore →</span></a><a className="card" href="/industries/restaurant-automation-kansas-city/"><span className="tag">Hospitality</span><h3>Restaurants & food service</h3><p>No-show reduction, review responses, social scheduling.</p><span className="more">Explore →</span></a></div></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="label">How we work</span><h2 style={{marginTop: '14px'}}>The same in Overland Park as everywhere.</h2></div></div><div className="card-grid card-grid--2"><div className="card"><span className="tag">Step 01</span><h3>$397 audit</h3><p>2–3 hours in your business. Ranked, written plan of every leak. Yours whether you DIY, hire us to teach you, or hire us to build it.</p></div><div className="card"><span className="tag">Step 02 (optional)</span><h3>Teach or Build</h3><p>You pick. Side-by-side training to run it yourself, or a fixed-bid done-for-you build starting at $500.</p></div></div></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Find your <em>leaks</em>, Overland Park.</h2><p className="sub">We drive to your business — same day for emergencies, this week for the rest. Overland Park is a ~25 minute drive from our base.</p><div className="actions"><a className="btn btn--invert" href="/contact/">Book a call <span className="arrow">→</span></a><a className="btn btn--ghost-invert" href="/services/system-audit-kansas-city/">Or book the audit</a></div></div></section>
    </main>
  );
}