import FaqAccordion from '../../components/FaqAccordion';

export const metadata = {
  title: 'AI Automation for Real Estate Agents in Kansas City | S.Y.S.T.E.M. KC',
  description: 'Lead nurture, 5-minute lead response, and cold-lead resurrection automation for Kansas City real estate agents and brokers.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">·</span><a href="/">Industries</a><span className="sep">·</span><span className="here">Real Estate Agents & Brokers</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">For Real Estate Agents & Brokers · Kansas City</span><h1>AI automation for <em>real estate agents</em> in Kansas City.</h1><p className="lede">Lead nurture is the killer app for real estate — and the one nobody actually does. You are with a client at 2pm, three new Zillow leads come in, and by the time you reach them at 9pm they have already toured with someone else. We make the follow-up automatic, in your voice, instantly.</p><div className="actions"><a className="btn btn--primary" href="/contact/">Book a 20-min call <span className="arrow">→</span></a><a className="btn btn--ghost" href="#automations">See what we build</a></div></div></header>
<section className="section"><div className="wrap"><div className="prose" style={{maxWidth: '72ch'}}><h2 style={{marginTop: '0'}}>You are not slow. You are busy.</h2><p>Real estate is a response-time business. <strong>Leads contacted within 5 minutes are 100× more likely to make contact</strong> than leads contacted after 30 minutes — and 78% of buyers go with whoever responds first. (That is Harvard/MIT research, not a marketing claim.)</p><p>The problem is not that agents are lazy. It is that you are with a client when the lead comes in. Your phone is in another room. You meant to circle back at lunch and it slipped. That is normal — and that is exactly why automation matters here more than almost anywhere.</p><p>The agents winning Kansas City right now are not the ones working harder. They are the ones whose lead-response systems are running while they are at the closing table.</p></div></div></section>
<section className="section section--alt" id="automations"><div className="wrap"><div className="section-head"><div><span className="label">What we build for real-estate</span><h2 style={{marginTop: '14px'}}>Built for agents and small teams.</h2></div></div><div className="card-grid"><div className="card"><span className="tag">01 · Speed-to-lead</span><h3>5-minute lead response</h3><p>Any new lead from Zillow, Realtor.com, your website, or social DMs gets a personalized text + email within 5 minutes — even if you are mid-showing. Custom messaging by lead source.</p></div><div className="card"><span className="tag">02 · Nurture</span><h3>Long-term lead nurture</h3><p>Buyers and sellers take months to act. Multi-touch nurture sequences keep you top-of-mind without you remembering to reach out. Pause/resume by activity.</p></div><div className="card"><span className="tag">03 · Booking</span><h3>Auto-scheduling for showings &amp; consults</h3><p>"When can we tour?" → calendar link → booked. Without 14 back-and-forth texts.</p></div><div className="card"><span className="tag">04 · Reactivation</span><h3>Cold lead resurrection</h3><p>Old leads from 6+ months ago re-engaged with a market-update sequence. Half the time you will get a "yeah, we are thinking about it again."</p></div><div className="card"><span className="tag">05 · Reviews</span><h3>Post-close review automation</h3><p>Closing day → automated review request → Google + Zillow + your testimonials page. The compounding effect of 30+ five-star reviews cannot be overstated.</p></div><div className="card"><span className="tag">06 · Listings</span><h3>New-listing alerts to buyer pool</h3><p>New active listing → matches your active buyer list → automated text with photos + scheduling link.</p></div></div></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="label">A day in the life</span><h2 style={{marginTop: '14px'}}>A solo agent, 6 months in.</h2></div></div><div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '48px'}}><div><h3 style={{fontFamily: 'var(--mono)', fontSize: '13px', letterSpacing: '.12em', color: '#D4322E', textTransform: 'uppercase', fontWeight: '700'}}>Before</h3><ul style={{marginLeft: '18px', color: 'var(--text)', fontSize: '17px', lineHeight: '1.7'}}><li>3 Zillow leads at 2pm. You are showing.</li><li>You text them back at 9:30pm. Two have already toured.</li><li>Last month's leads sit in a spreadsheet you stopped opening.</li><li>You close ~2 deals/mo on luck and referrals.</li></ul></div><div><h3 style={{fontFamily: 'var(--mono)', fontSize: '13px', letterSpacing: '.12em', color: '#1F8A99', textTransform: 'uppercase', fontWeight: '700'}}>After</h3><ul style={{marginLeft: '18px', color: 'var(--text)', fontSize: '17px', lineHeight: '1.7'}}><li>Lead arrives → personalized text in &lt;5 min.</li><li>Nurture sequence runs for 6 weeks if they do not book.</li><li>Old leads get a market-update text quarterly — 1 in 8 re-engages.</li><li>You close 4–5/mo. Same hours. More referrals from happy reviews.</li></ul></div></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common questions</span><h2 style={{marginTop: '14px'}}>From real-estate owners.</h2></div></div><FaqAccordion><div className="faq-item open"><button className="faq-q"><span className="qnum">Q.01</span><span className="qtxt">Will this work with my brokerage's CRM?</span><span className="qicn">+</span></button><div className="faq-a">Usually yes — we integrate alongside it. If your brokerage uses a closed system, we will work around the edges so you do not have duplicate data entry.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.02</span><span className="qtxt">Is this just an auto-responder?</span><span className="qicn">+</span></button><div className="faq-a">No. The first response feels personal because it is — written in your voice, referencing the property they asked about. We use AI to compose, not to template.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.03</span><span className="qtxt">What about TCPA / SMS consent?</span><span className="qicn">+</span></button><div className="faq-a">Every form has the proper consent language baked in. Lead-source integrations only enroll people in SMS sequences when consent is captured at source. We do this right.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.04</span><span className="qtxt">Pricing?</span><span className="qicn">+</span></button><div className="faq-a">Most solo agents land in a $500–$1,000 build + $450/mo retainer that covers their subscriptions. Teams scale up from there.</div></div></FaqAccordion></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Win the <em>5-minute window</em>.</h2><p className="sub">$397 in-person audit. We come to your office, find the 3 biggest leaks, and you walk away with a ranked plan. Yours whether you hire us to build it or not.</p><div className="actions"><a className="btn btn--invert" href="/contact/">Book the audit <span className="arrow">→</span></a></div></div></section>
    </main>
  );
}