import FaqAccordion from '../../components/FaqAccordion';

export const metadata = {
  title: 'The 60-Day Profit Challenge for Real Estate Agents | S.Y.S.T.E.M. KC',
  description: 'Add $20,000 in new commission in 60 days — guaranteed. Live 1-on-1 business growth training for real estate agents and brokers.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">&middot;</span><a href="/industries/">Industries</a><span className="sep">&middot;</span><span className="here">Real Estate Agents &amp; Brokers</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">For Real Estate Agents &amp; Brokers </span><h1>The 60-Day Real Estate $20,000 Profit Challenge</h1><p className="lede">You are showing at 2pm when three Zillow leads come in. By 9pm when you text back, two have already toured with someone else. The 60-Day Profit Challenge teaches real estate agents how to fix their offer, their follow-up model, and their referral engine &mdash; so they close more deals without working more hours.</p><p className="nat-sub" style={{fontStyle: 'italic'}}>Add $20,000 in new revenue in 60 days &mdash; or I work for free until you do.</p><div className="actions"><a className="btn btn--primary" href="/apply/">Apply Now &rarr;</a><a className="btn btn--ghost" href="/the-challenge/">See the Challenge</a></div></div></header>
{/* WHO THIS IS FOR + GUARANTEE */}
      <section style={{background: 'var(--bg-green-tint)', padding: '80px 0', borderBottom: '1px solid var(--rule)'}}>
        <div className="wrap">
          <div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '64px', alignItems: 'center'}}>
            <div>
              <p style={{fontFamily: 'var(--mono)', fontSize: '12px', letterSpacing: '.18em', textTransform: 'uppercase', color: 'var(--green)', fontWeight: '700', marginBottom: '20px'}}>Who this is for</p>
              <h2 style={{fontFamily: 'var(--sans)', fontSize: 'clamp(28px, 3.5vw, 46px)', fontWeight: '900', lineHeight: '1.1', letterSpacing: '-.03em', color: 'var(--blue-deep)'}}>Built for agents who are done losing deals to their own schedule.</h2>
              <p style={{marginTop: '24px', fontSize: '18px', lineHeight: '1.75', color: 'var(--muted)'}}>Real estate agents didn&rsquo;t leave a W-2 to miss leads because they were in a showing. The response gap isn&rsquo;t a discipline problem &mdash; it&rsquo;s a systems problem. The drive is there. The follow-up engine is missing.</p>
              <p style={{marginTop: '16px', fontFamily: 'var(--serif)', fontStyle: 'italic', fontSize: '22px', color: 'var(--blue-deep)', lineHeight: '1.35'}}>Success in real estate isn&rsquo;t about working more transactions &mdash; it&rsquo;s about building the system that closes them while you&rsquo;re at the closing table.</p>
            </div>
            <div style={{background: 'var(--blue-deep)', borderRadius: '20px', padding: '44px 40px', textAlign: 'center'}}>
              <p style={{fontFamily: 'var(--mono)', fontSize: '11px', letterSpacing: '.18em', textTransform: 'uppercase', color: 'var(--green)', fontWeight: '700', marginBottom: '8px'}}>The 60-Day Real Estate Profit Challenge &mdash; Guarantee</p>
              <div style={{fontFamily: 'var(--serif)', fontSize: 'clamp(56px, 8vw, 88px)', fontWeight: '900', lineHeight: '1', color: '#fff', letterSpacing: '-.03em'}}>$20,000</div>
              <p style={{marginTop: '16px', fontSize: '19px', fontWeight: '700', color: '#fff', lineHeight: '1.4'}}>in new revenue in 60 days &mdash; or I work for free until you do.</p>
              <p style={{marginTop: '14px', fontSize: '14px', color: 'rgba(255,255,255,.6)', lineHeight: '1.6'}}>No contracts. No fine print. We build your money model, marketing, sales system, referrals, and operations together &mdash; live and 1-on-1. If it doesn&rsquo;t produce, I keep working at no extra cost.</p>
              <div style={{marginTop: '28px', display: 'flex', flexDirection: 'column', gap: '10px', alignItems: 'center'}}>
                <a className="btn btn--primary" href="/apply/" style={{width: '100%', justifyContent: 'center', fontSize: '17px', padding: '16px 24px'}}>Apply for a free fit call &rarr;</a>
                <a href="/the-challenge/" style={{fontSize: '13px', color: 'rgba(255,255,255,.5)', fontFamily: 'var(--mono)', letterSpacing: '.06em'}}>See everything included in the Challenge &rarr;</a>
              </div>
            </div>
          </div>
        </div>
      </section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Inside the 60-Day Challenge</span><h2 style={{marginTop: '14px'}}>Built for real estate agents who want to close more without working more.</h2></div></div><div className="card-grid"><div className="card"><span className="tag">01 &middot; Agent Positioning</span><h3>Who you are for and why they should hire you</h3><p>Niche clarity, geographic focus, offer differentiation. Most agents compete on commission. We fix the positioning so you compete on results and close more consultations without discounting.</p></div><div className="card"><span className="tag">02 &middot; Lead Generation</span><h3>More qualified leads from the right channels</h3><p>Google presence, social, referral source mapping, past-client reactivation strategy. We map where your buyers and sellers are coming from and build the system that keeps qualified leads flowing.</p></div><div className="card"><span className="tag">03 &middot; Speed-to-Lead</span><h3>The agent who responds in 5 minutes wins the listing</h3><p>Every new inquiry gets a personalized response in under 5 minutes &mdash; even when you are mid-showing. We build the response system that means you are always first, not second.</p></div><div className="card"><span className="tag">04 &middot; Lead Nurture</span><h3>Buyers and sellers take months to act. Stay in front of them.</h3><p>Long-term follow-up sequences, market-update touchpoints, re-engagement campaigns for cold leads. Most agents lose the deal because they stopped following up two months before the client was ready.</p></div><div className="card"><span className="tag">05 &middot; Reviews &amp; Referrals</span><h3>30+ five-star reviews changes your business</h3><p>Post-close review requests, referral program mechanics, past-client advocacy system. Most referrals happen by accident. We make them a predictable channel.</p></div><div className="card"><span className="tag">06 &middot; Systems &amp; Operations</span><h3>Close more without working more hours</h3><p>Showing workflow, offer management, closing follow-up, buyer and seller communication SOPs. We build the operational layer so you can run 2&times; the deals without 2&times; the chaos.</p></div></div></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="label">A day in the life</span><h2 style={{marginTop: '14px'}}>A solo agent, 6 months in.</h2></div></div><div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '48px'}}><div><h3 style={{fontFamily: 'var(--mono)', fontSize: '13px', letterSpacing: '.12em', color: '#D4322E', textTransform: 'uppercase', fontWeight: '700'}}>Before</h3><ul style={{marginLeft: '18px', color: 'var(--text)', fontSize: '17px', lineHeight: '1.7'}}><li>3 Zillow leads at 2pm. You are showing.</li><li>You text them back at 9:30pm. Two have already toured.</li><li>Last month&rsquo;s leads sit in a spreadsheet you stopped opening.</li><li>You close ~2 deals/mo on luck and referrals.</li></ul></div><div><h3 style={{fontFamily: 'var(--mono)', fontSize: '13px', letterSpacing: '.12em', color: '#1F8A99', textTransform: 'uppercase', fontWeight: '700'}}>After</h3><ul style={{marginLeft: '18px', color: 'var(--text)', fontSize: '17px', lineHeight: '1.7'}}><li>Lead arrives &rarr; personalized text in &lt;5 min.</li><li>Nurture sequence runs for 6 weeks if they do not book.</li><li>Old leads get a market-update text quarterly &mdash; 1 in 8 re-engages.</li><li>You close 4&ndash;5/mo. Same hours. More referrals from happy reviews.</li></ul></div></div></div></section>
<section style={{background: 'var(--bg-green-tint)', padding: '80px 0'}}><div className="wrap" style={{display: 'flex', justifyContent: 'center'}}><div style={{maxWidth: '560px', background: 'var(--blue-deep)', borderRadius: '16px', padding: '48px', color: '#fff'}}><span style={{fontFamily: 'var(--mono)', fontSize: '11px', letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--green)', fontWeight: '700', display: 'block', marginBottom: '24px'}}>The 60-Day Profit Challenge &mdash; Guarantee</span><div style={{fontSize: 'clamp(52px, 7vw, 80px)', fontWeight: '900', fontFamily: 'var(--sans)', lineHeight: '1', color: '#fff', letterSpacing: '-.04em', marginBottom: '24px'}}>$20,000</div><p style={{fontSize: '17px', lineHeight: '1.7', color: 'rgba(255,255,255,0.88)', marginBottom: '32px'}}>If you do not add $20,000 in new commission within 60 days, I keep working with you &mdash; live, 1-on-1 &mdash; for free until you do. No service credit. No conditions. I work for free until the number is hit.</p><div className="actions"><a className="btn btn--primary" href="/apply/">Apply Now &rarr;</a><a className="btn btn--ghost-invert" href="/the-challenge/">See everything in the Challenge</a></div></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common questions</span><h2 style={{marginTop: '14px'}}>From real estate agents.</h2></div></div><FaqAccordion><div className="faq-item open"><button className="faq-q"><span className="qnum">Q.01</span><span className="qtxt">What exactly is the 60-Day Profit Challenge?</span><span className="qicn">+</span></button><div className="faq-a">The 60-Day Profit Challenge is a live, 1-on-1 business growth program for real estate agents and small teams. Over 60 days, we work through your positioning, lead generation, response systems, nurture sequences, and referral engine &mdash; together, in live sessions, built around your specific business. Not a CRM training. Not a course. Real strategy built for your market.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.02</span><span className="qtxt">What does the Challenge focus on for real estate specifically?</span><span className="qicn">+</span></button><div className="faq-a">For real estate agents, the Challenge focuses on the highest-leverage moves: speed-to-lead (the single biggest factor in conversion), long-term lead nurture, positioning that wins the listing without discounting, and a referral and review engine that compounds over time. We have worked with agents across the country and the playbook is built for how a solo agent or small team actually runs their business.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.03</span><span className="qtxt">Is this a course or a done-for-you service?</span><span className="qicn">+</span></button><div className="faq-a">Neither &mdash; it is a working engagement. We build the actual growth strategy for your business, install the systems, and stay in live sessions until $20,000 in new revenue is added. You are not watching videos. You are building with a real operator.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.04</span><span className="qtxt">What happens if I don&rsquo;t hit $20,000 in 60 days?</span><span className="qicn">+</span></button><div className="faq-a">If you do not add $20,000 in new revenue within 60 days, I keep working with you &mdash; live, 1-on-1 &mdash; for free until you do. No service credit. No conditions. I work for free until the number is hit.</div></div></FaqAccordion></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Ready to add $20,000 in new <em>commission</em>?</h2><p className="sub">Apply to see if you qualify. First conversation is free.</p><div className="actions"><a className="btn btn--invert" href="/apply/">Apply Now &rarr;</a></div></div></section>
    </main>
  );
}
