import FaqAccordion from '../../components/FaqAccordion';

export const metadata = {
  title: 'Appointment & Admin Automation for KC Medical & Dental Practices | S.Y.S.T.E.M. KC',
  description: 'Appointment reminders, new-patient intake, review collection and treatment-plan follow-up for Kansas City medical and dental practices. We do not touch HIPAA-governed systems.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">·</span><a href="/">Industries</a><span className="sep">·</span><span className="here">Medical, Dental & Healthcare</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">For Medical, Dental & Healthcare · Kansas City</span><h1>Appointment &amp; admin <em>automation</em> for KC medical &amp; dental practices.</h1><p className="lede">Healthcare is Kansas City's largest employer sector. The biggest revenue leak in most KC practices is not marketing — it is the no-show. We build the appointment, intake, and review-collection layer around your EHR. We do not touch HIPAA-governed clinical data — just the operational layer.</p><div className="actions"><a className="btn btn--primary" href="/contact/">Book a 20-min call <span className="arrow">→</span></a><a className="btn btn--ghost" href="#automations">See what we build</a></div></div></header>
<section className="section"><div className="wrap"><div className="prose" style={{maxWidth: '72ch'}}><h2 style={{marginTop: '0'}}>No-shows are the ROI story.</h2><p>The American Dental Association puts the average no-show rate around 15–17%. <strong>One missed appointment a day in a 4-chair practice is roughly $80,000 a year in lost capacity.</strong></p><p>The fix is well-known: multi-touch reminders, easy rescheduling, gentle accountability. Most practices know this. What stops them is that their EHR has a reminder feature that is either too rigid or too generic, and nobody has time to build something better.</p><p>We bolt on a layer that handles reminders, rescheduling, new-patient intake, and review collection — without touching anything HIPAA-governed. We are not in your EHR. We are around it.</p></div></div></section>
<section className="section section--alt" id="automations"><div className="wrap"><div className="section-head"><div><span className="label">What we build for practice</span><h2 style={{marginTop: '14px'}}>Built for medical and dental practices in the KC region.</h2></div></div><div className="card-grid"><div className="card"><span className="tag">01 · Reminders</span><h3>Multi-touch appointment reminders</h3><p>Appointment booked → email confirm immediately → SMS at -7d, -2d, -2h. Easy reschedule link in each. Drops no-shows by 30–50% in our KC dental clients.</p></div><div className="card"><span className="tag">02 · Intake</span><h3>New-patient intake forms</h3><p>Booking complete → patient gets intake forms by SMS link → fills them out on their phone before the visit. Saves 15 min of waiting-room paperwork per new patient.</p></div><div className="card"><span className="tag">03 · Reviews</span><h3>Post-visit review request</h3><p>Visit complete → automated text the morning after → direct link to Google. Steady review velocity = better map-pack ranking = more new-patient calls.</p></div><div className="card"><span className="tag">04 · Recall</span><h3>Recare reminder sequence</h3><p>6-month cleaning due? Automated sequence books it without front-desk effort. Fills the schedule weeks ahead.</p></div><div className="card"><span className="tag">05 · Outreach</span><h3>Treatment-plan follow-up</h3><p>Patient accepted a treatment plan but has not scheduled? Polite weekly sequence until booked. Recovers 20–30% of pending treatment.</p></div><div className="card"><span className="tag">06 · Front desk</span><h3>Missed-call text-back</h3><p>Front desk on the phone with another patient? Missed call gets a "we will call you right back" text within 30 seconds. Nobody is left wondering if you got their message.</p></div></div></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="label">A day in the life</span><h2 style={{marginTop: '14px'}}>A 4-chair KC dental practice, 90 days in.</h2></div></div><div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '48px'}}><div><h3 style={{fontFamily: 'var(--mono)', fontSize: '13px', letterSpacing: '.12em', color: '#D4322E', textTransform: 'uppercase', fontWeight: '700'}}>Before</h3><ul style={{marginLeft: '18px', color: 'var(--text)', fontSize: '17px', lineHeight: '1.7'}}><li>17% no-show rate. ~$80k/yr lost capacity.</li><li>Front desk doing manual reminder calls all morning.</li><li>4 reviews/month, mostly from the front-desk lady asking.</li><li>Treatment plans accepted but not booked.</li></ul></div><div><h3 style={{fontFamily: 'var(--mono)', fontSize: '13px', letterSpacing: '.12em', color: '#1F8A99', textTransform: 'uppercase', fontWeight: '700'}}>After</h3><ul style={{marginLeft: '18px', color: 'var(--text)', fontSize: '17px', lineHeight: '1.7'}}><li>No-show rate at 7%. Recovered ~$45k/yr.</li><li>Front desk handles patient relationships, not robocalls.</li><li>22 reviews/month. Map-pack ranking up 6 positions.</li><li>Pending treatment value down 40%.</li></ul></div></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common questions</span><h2 style={{marginTop: '14px'}}>From practice owners.</h2></div></div><FaqAccordion><div className="faq-item open"><button className="faq-q"><span className="qnum">Q.01</span><span className="qtxt">Will you touch our EHR or PMS?</span><span className="qicn">+</span></button><div className="faq-a">No. Deliberately. We work around it, not inside it. That keeps you clear of any HIPAA compliance issues with our work — anything HIPAA-governed stays in your existing systems.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.02</span><span className="qtxt">What about patient consent for SMS?</span><span className="qicn">+</span></button><div className="faq-a">Every patient enrolled in SMS reminders has consented at booking. Opt-out is one tap. We architect this carefully because we have to.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.03</span><span className="qtxt">Will the AI feel impersonal?</span><span className="qicn">+</span></button><div className="faq-a">No — it sounds like your practice. We train it on your voice and tone. Patients tell us they did not realize it was automated.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.04</span><span className="qtxt">Pricing?</span><span className="qicn">+</span></button><div className="faq-a">Practices typically land in a $1,500–$4,000 build plus a $450–$900/mo retainer.</div></div></FaqAccordion></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Recover your <em>no-show losses</em>.</h2><p className="sub">$397 in-person audit. We come to your practice, find the 3 biggest leaks, and you walk away with a ranked plan. Yours whether you hire us to build it or not.</p><div className="actions"><a className="btn btn--invert" href="/contact/">Book the audit <span className="arrow">→</span></a></div></div></section>
    </main>
  );
}