import FaqAccordion from '../../components/FaqAccordion';

export const metadata = {
  title: 'The 60-Day Profit Challenge for Medical & Dental Practice Owners | S.Y.S.T.E.M. KC',
  description: 'Live 1-on-1 business growth training for practice owners. Reduce no-shows, grow new-patient volume, increase treatment acceptance, and add $20,000 in recovered practice revenue in 60 days — guaranteed.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">&middot;</span><a href="/industries/">Industries</a><span className="sep">&middot;</span><span className="here">Medical, Dental &amp; Healthcare</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">For Medical, Dental &amp; Healthcare </span><h1>Fill the empty chair. Add $20,000 in recovered practice revenue in 60 days.</h1><p className="lede">One missed appointment a day in a 4-chair dental practice is roughly $80,000 a year in lost capacity. The 60-Day Profit Challenge teaches practice owners how to fix the revenue model, reduce no-shows, grow new-patient volume, and build a practice that fills itself.</p><p className="sub">Add $20,000 in new revenue in 60 days &mdash; or I work for free until you do.</p><div className="actions"><a className="btn btn--primary" href="/apply/">Apply Now &rarr;</a><a className="btn btn--ghost" href="/the-challenge/">See the Challenge</a></div></div></header>
<section className="section"><div className="wrap"><div className="prose" style={{maxWidth: '72ch'}}><h2 style={{marginTop: '0'}}>No-shows are the ROI story.</h2><p>The American Dental Association puts the average no-show rate around 15&ndash;17%. <strong>One missed appointment a day in a 4-chair practice is roughly $80,000 a year in lost capacity.</strong></p><p>The fix is well-known: multi-touch reminders, easy rescheduling, gentle accountability. Most practices know this. What stops them is that their EHR has a reminder feature that is either too rigid or too generic, and nobody has time to build something better.</p><p>Beyond no-shows: accepted treatment plans that never get scheduled, recall patients who fall through the cracks, new-patient volume that stalls because reviews are not coming in. Every one of these is a revenue leak with a known process solution. That is exactly what the 60-Day Challenge is built to address.</p></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Inside the 60-Day Challenge</span><h2 style={{marginTop: '14px'}}>Medical &amp; dental practice growth &mdash; built for practice owners.</h2></div></div><div className="card-grid"><div className="card"><span className="tag">01 &middot; Offer &amp; Fee Structure</span><h3>Most practices are leaving money in unaccepted treatment plans</h3><p>Treatment acceptance rate, fee presentation, service bundling, membership plan design. We fix the offer so the same patient visits produce more accepted revenue.</p></div><div className="card"><span className="tag">02 &middot; New Patient Acquisition</span><h3>More of the right patients finding you first</h3><p>Google Business Profile, local SEO, review velocity, referral source mapping. We build the acquisition system that puts you at the top of the map when someone searches for a dentist or doctor near them.</p></div><div className="card"><span className="tag">03 &middot; No-Show Reduction</span><h3>Every empty chair is money that cannot be recovered</h3><p>Multi-touch appointment reminders, easy reschedule flows, confirmation sequences. Practices typically cut their no-show rate by 40&ndash;60% inside 60 days.</p></div><div className="card"><span className="tag">04 &middot; Treatment Acceptance</span><h3>Accepted treatment plans that never get scheduled are lost revenue</h3><p>Pending treatment follow-up sequences, easy scheduling flows, treatment presentation scripts. We recover 20&ndash;30% of accepted but unbooked treatment value.</p></div><div className="card"><span className="tag">05 &middot; Recall &amp; Retention</span><h3>Your existing patients are your highest-margin acquisition channel</h3><p>Recare reminder sequences, return-visit triggers, lapsed-patient reactivation. We build the system that keeps your schedule full weeks in advance without front-desk effort.</p></div><div className="card"><span className="tag">06 &middot; Reviews &amp; Referrals</span><h3>More 5-star reviews = more new-patient calls</h3><p>Post-visit review requests, referral program mechanics, patient advocacy system. Steady review velocity keeps you at the top of the map pack and makes every new patient easier to earn.</p></div></div></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="label">A day in the life</span><h2 style={{marginTop: '14px'}}>A 4-chair dental practice, 90 days in.</h2></div></div><div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '48px'}}><div><h3 style={{fontFamily: 'var(--mono)', fontSize: '13px', letterSpacing: '.12em', color: '#D4322E', textTransform: 'uppercase', fontWeight: '700'}}>Before</h3><ul style={{marginLeft: '18px', color: 'var(--text)', fontSize: '17px', lineHeight: '1.7'}}><li>17% no-show rate. ~$80k/yr lost capacity.</li><li>Front desk doing manual reminder calls all morning.</li><li>4 reviews/month, mostly from the front-desk lady asking.</li><li>Treatment plans accepted but not booked.</li></ul></div><div><h3 style={{fontFamily: 'var(--mono)', fontSize: '13px', letterSpacing: '.12em', color: '#1F8A99', textTransform: 'uppercase', fontWeight: '700'}}>After</h3><ul style={{marginLeft: '18px', color: 'var(--text)', fontSize: '17px', lineHeight: '1.7'}}><li>No-show rate at 7%. Recovered ~$45k/yr.</li><li>Front desk handles patient relationships, not robocalls.</li><li>22 reviews/month. Map-pack ranking up 6 positions.</li><li>Pending treatment value down 40%.</li></ul></div></div></div></section>
<section style={{background: 'var(--bg-green-tint)', padding: '80px 0'}}><div className="wrap" style={{display: 'flex', justifyContent: 'center'}}><div style={{maxWidth: '560px', background: 'var(--blue-deep)', borderRadius: '16px', padding: '48px', color: '#fff'}}><span style={{fontFamily: 'var(--mono)', fontSize: '11px', letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--green)', fontWeight: '700', display: 'block', marginBottom: '24px'}}>The 60-Day Profit Challenge &mdash; Guarantee</span><div style={{fontSize: 'clamp(52px, 7vw, 80px)', fontWeight: '900', fontFamily: 'var(--sans)', lineHeight: '1', color: '#fff', letterSpacing: '-.04em', marginBottom: '24px'}}>$20,000</div><p style={{fontSize: '18px', lineHeight: '1.65', marginBottom: '32px', color: 'rgba(255,255,255,0.88)'}}>If you do not add $20,000 in new revenue to your practice within 60 days, I keep working with you &mdash; live, 1-on-1 &mdash; for free until you do. No service credit. No conditions. I work for free until the number is hit.</p><div className="actions"><a className="btn btn--primary" href="/apply/">Apply Now &rarr;</a><a className="btn btn--ghost-invert" href="/the-challenge/">See everything in the Challenge</a></div></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common questions</span><h2 style={{marginTop: '14px'}}>From practice owners.</h2></div></div><FaqAccordion><div className="faq-item open"><button className="faq-q"><span className="qnum">Q.01</span><span className="qtxt">What exactly is the 60-Day Profit Challenge?</span><span className="qicn">+</span></button><div className="faq-a">The 60-Day Profit Challenge is a live, 1-on-1 business growth program for practice owners. Over 60 days, we work through your revenue model, new-patient acquisition, no-show reduction, treatment acceptance, recall systems, and referral engine &mdash; together, in live sessions, built around your specific practice. Not a course. Real strategy, real work.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.02</span><span className="qtxt">What does the Challenge focus on for medical and dental practices?</span><span className="qicn">+</span></button><div className="faq-a">For medical and dental practices, the Challenge focuses on the highest-leverage revenue moves: reducing no-shows (the single biggest revenue leak in most practices), increasing treatment acceptance, growing new-patient volume through reviews and referrals, and building the recall and retention system that fills the schedule without front-desk effort. We work around your EHR &mdash; we are not inside it.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.03</span><span className="qtxt">Is this a course or a consulting retainer?</span><span className="qicn">+</span></button><div className="faq-a">Neither &mdash; it is a working engagement. We build the actual growth strategy for your practice, install the systems, and stay in live sessions until $20,000 in new revenue is added. You are not watching videos. You are building with a real operator.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.04</span><span className="qtxt">What is the guarantee, exactly?</span><span className="qicn">+</span></button><div className="faq-a">If you do not add $20,000 in new revenue within 60 days, I keep working with you &mdash; live, 1-on-1 &mdash; for free until you do. No service credit. No conditions. I work for free until the number is hit.</div></div></FaqAccordion></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Ready to fill the <em>empty chairs</em>?</h2><p className="sub">Apply to see if your practice qualifies. First conversation is free.</p><div className="actions"><a className="btn btn--invert" href="/apply/">Apply Now &rarr;</a></div></div></section>
    </main>
  );
}
