import FaqAccordion from '../../components/FaqAccordion';

export const metadata = {
  title: 'Booking & Review Automation for KC Salons & Spas | S.Y.S.T.E.M. KC',
  description: '24/7 online booking, no-show reduction reminders, and review automation for Kansas City salons and spas. Bookings, no-shows, reviews — the three numbers that run the business.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">·</span><a href="/">Industries</a><span className="sep">·</span><span className="here">Salons, Spas & Personal Care</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">For Salons, Spas & Personal Care · Kansas City</span><h1>Booking &amp; review <em>automation</em> for KC salons &amp; spas.</h1><p className="lede">In personal care, three things run the entire business: bookings, no-shows, and reviews. We automate all three so you can focus on the work and the client in your chair — not on the phone, the social account, or the constant chase.</p><div className="actions"><a className="btn btn--primary" href="/contact/">Book a 20-min call <span className="arrow">→</span></a><a className="btn btn--ghost" href="#automations">See what we build</a></div></div></header>
<section className="section"><div className="wrap"><div className="prose" style={{maxWidth: '72ch'}}><h2 style={{marginTop: '0'}}>Three numbers run the business.</h2><p>Bookings, no-shows, reviews. Get those three numbers right and the rest of the business takes care of itself.</p><p>Most KC salons we audit are losing on at least two of them: <strong>15%+ no-show rate</strong> (industry research suggests reminders cut this by 30–40%), inconsistent review velocity hurting their Google ranking, and a booking flow that requires 4 DMs and a phone call.</p><p>The fix is not complicated. The reason it does not get fixed is that you are already in someone's chair when the problem happens. So we build the layer that handles bookings, sends the reminders, requests the reviews, and posts to social — while you are doing the actual work that pays.</p></div></div></section>
<section className="section section--alt" id="automations"><div className="wrap"><div className="section-head"><div><span className="label">What we build for salon</span><h2 style={{marginTop: '14px'}}>Built for solo stylists and small-team salons.</h2></div></div><div className="card-grid"><div className="card"><span className="tag">01 · Booking</span><h3>24/7 online booking</h3><p>Client texts "need a fill" at 11pm → guided to your real-time availability → booked. Without you opening your phone.</p></div><div className="card"><span className="tag">02 · Reminders</span><h3>No-show reduction sequence</h3><p>Appointment booked → confirm immediately → reminder 24h before with easy reschedule → final reminder 2h before. Cuts no-shows 30–50%.</p></div><div className="card"><span className="tag">03 · Reviews</span><h3>Post-service review request</h3><p>Service complete → automated text the next morning → direct link to Google. Builds the consistent 5-star feed that fills the chair.</p></div><div className="card"><span className="tag">04 · Social</span><h3>Before/after content scheduling</h3><p>Snap the photo, drop it in our system, AI drafts the caption in your voice. Approve and schedule a week of content in 15 minutes.</p></div><div className="card"><span className="tag">05 · Retention</span><h3>Rebooking + return-visit sequence</h3><p>Have not seen a client in 8 weeks? Gentle "ready for your next?" text. Keeps the chair full and clients on schedule.</p></div><div className="card"><span className="tag">06 · Promotions</span><h3>Birthday + slow-day offers</h3><p>Birthday in 5 days → special offer. Slow Tuesday afternoon → text VIP clients with a same-day opening. Fill the gaps that hurt revenue.</p></div></div></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="label">A day in the life</span><h2 style={{marginTop: '14px'}}>A 2-chair KC salon, 90 days in.</h2></div></div><div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '48px'}}><div><h3 style={{fontFamily: 'var(--mono)', fontSize: '13px', letterSpacing: '.12em', color: '#D4322E', textTransform: 'uppercase', fontWeight: '700'}}>Before</h3><ul style={{marginLeft: '18px', color: 'var(--text)', fontSize: '17px', lineHeight: '1.7'}}><li>Booking via Instagram DM. 14 messages per appointment.</li><li>~16% no-show rate on weekend slots.</li><li>~3 Google reviews/month.</li><li>Stylist spends 10 hr/week on phone/admin work.</li></ul></div><div><h3 style={{fontFamily: 'var(--mono)', fontSize: '13px', letterSpacing: '.12em', color: '#1F8A99', textTransform: 'uppercase', fontWeight: '700'}}>After</h3><ul style={{marginLeft: '18px', color: 'var(--text)', fontSize: '17px', lineHeight: '1.7'}}><li>Online booking handles 80%+ of appointments.</li><li>No-show rate at 6%. Weekend revenue up 22%.</li><li>~18 Google reviews/month. Top of the local search.</li><li>Stylist gets the 10 hours back. Adds Friday appointments.</li></ul></div></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common questions</span><h2 style={{marginTop: '14px'}}>From salon owners.</h2></div></div><FaqAccordion><div className="faq-item open"><button className="faq-q"><span className="qnum">Q.01</span><span className="qtxt">Will this replace my booking software?</span><span className="qicn">+</span></button><div className="faq-a">Usually not. We integrate with your existing booking system (Vagaro, GlossGenius, Square, Boulevard, etc.) — automation runs around it.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.02</span><span className="qtxt">Will the reminders feel pushy?</span><span className="qicn">+</span></button><div className="faq-a">No. We tune tone carefully. Clients tell us the reminders feel helpful, not corporate.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.03</span><span className="qtxt">What about my walk-ins?</span><span className="qicn">+</span></button><div className="faq-a">Walk-ins still flow normally. The automation handles booked appointments and digital leads — your in-person clients are not affected.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.04</span><span className="qtxt">Pricing?</span><span className="qicn">+</span></button><div className="faq-a">Most KC salons land in a $500–$1,500 build plus a $450/mo retainer that covers your subscriptions.</div></div></FaqAccordion></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Fill the <em>chair</em>.</h2><p className="sub">$397 in-person audit. We come to your salon, find the 3 biggest leaks, and you walk away with a ranked plan. Yours whether you hire us to build it or not.</p><div className="actions"><a className="btn btn--invert" href="/contact/">Book the audit <span className="arrow">→</span></a></div></div></section>
    </main>
  );
}