import FaqAccordion from '../../components/FaqAccordion';

export const metadata = {
  title: 'The 60-Day Profit Challenge for Salon & Spa Owners | S.Y.S.T.E.M. KC',
  description: 'Add $20,000 in new salon revenue in 60 days — guaranteed. Live 1-on-1 business growth training for salon and spa owners.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">&middot;</span><a href="/industries/">Industries</a><span className="sep">&middot;</span><span className="here">Salons, Spas &amp; Personal Care</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">For Salons, Spas &amp; Personal Care </span><h1>Fill the chair, cut the no-shows, add $20,000 in salon revenue in 60 days.</h1><p className="lede">Three things run a salon: bookings, no-shows, and reviews. Most salons we work with are losing on at least two. The 60-Day Profit Challenge teaches salon owners how to fix their offer, fill the chair consistently, and build a business that grows without them doing everything by hand.</p><p className="nat-sub" style={{fontStyle: 'italic'}}>Add $20,000 in new revenue in 60 days &mdash; or I work for free until you do.</p><div className="actions"><a className="btn btn--primary" href="/apply/">Apply Now &rarr;</a><a className="btn btn--ghost" href="/the-challenge/">See the Challenge</a></div></div></header>
<section className="section"><div className="wrap"><div className="prose" style={{maxWidth: '72ch'}}><h2 style={{marginTop: '0'}}>Three numbers run the business.</h2><p>Bookings, no-shows, reviews. Get those three numbers right and the rest of the business takes care of itself.</p><p>Most salons we audit are losing on at least two of them: <strong>15%+ no-show rate</strong> (industry research suggests reminders cut this by 30&ndash;40%), inconsistent review velocity hurting their Google ranking, and a booking flow that requires 4 DMs and a phone call.</p><p>The 60-Day Challenge is built to fix all three &mdash; and the revenue that falls out of fixing them.</p></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Inside the 60-Day Challenge</span><h2 style={{marginTop: '14px'}}>Built for salon owners who want more revenue without more chaos.</h2></div></div><div className="card-grid"><div className="card"><span className="tag">01 &middot; Offer &amp; Service Pricing</span><h3>Most salons undercharge and over-discount</h3><p>Service menu structure, pricing tiers, retail add-on offers, package design. We fix the offer so the same chair produces more revenue per visit without you adding hours.</p></div><div className="card"><span className="tag">02 &middot; Client Acquisition</span><h3>Get found by more local clients</h3><p>Google Business Profile, Instagram, local SEO, Yelp. We build the acquisition system that keeps new clients finding you first when they search for a salon in your area.</p></div><div className="card"><span className="tag">03 &middot; Booking &amp; Availability</span><h3>Every missed booking request is revenue that went somewhere else</h3><p>24/7 online booking, waitlist management, booking-flow optimization. Clients can book at 11pm without you opening your phone.</p></div><div className="card"><span className="tag">04 &middot; No-Show Reduction</span><h3>A no-show at peak hours is your worst revenue leak</h3><p>Multi-touch appointment reminders, easy reschedule links, confirmation sequences. Most salons cut their no-show rate by 40&ndash;60% inside 60 days.</p></div><div className="card"><span className="tag">05 &middot; Retention &amp; Rebooking</span><h3>A client who comes back every 8 weeks is worth 6&times; a one-time visitor</h3><p>Return-visit triggers, rebooking flows, lapsed-client reactivation. We build the system that keeps your regulars on a schedule without you chasing them.</p></div><div className="card"><span className="tag">06 &middot; Reviews &amp; Referrals</span><h3>Your best clients should be sending you their friends</h3><p>Post-service review requests, referral program mechanics, client advocacy system. Consistent 5-star reviews fill the chair before you spend a dollar on ads.</p></div></div></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="label">A day in the life</span><h2 style={{marginTop: '14px'}}>A 2-chair salon, 90 days in.</h2></div></div><div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '48px'}}><div><h3 style={{fontFamily: 'var(--mono)', fontSize: '13px', letterSpacing: '.12em', color: '#D4322E', textTransform: 'uppercase', fontWeight: '700'}}>Before</h3><ul style={{marginLeft: '18px', color: 'var(--text)', fontSize: '17px', lineHeight: '1.7'}}><li>Booking via Instagram DM. 14 messages per appointment.</li><li>~16% no-show rate on weekend slots.</li><li>~3 Google reviews/month.</li><li>Stylist spends 10 hr/week on phone/admin work.</li></ul></div><div><h3 style={{fontFamily: 'var(--mono)', fontSize: '13px', letterSpacing: '.12em', color: '#1F8A99', textTransform: 'uppercase', fontWeight: '700'}}>After</h3><ul style={{marginLeft: '18px', color: 'var(--text)', fontSize: '17px', lineHeight: '1.7'}}><li>Online booking handles 80%+ of appointments.</li><li>No-show rate at 6%. Weekend revenue up 22%.</li><li>~18 Google reviews/month. Top of the local search.</li><li>Stylist gets the 10 hours back. Adds Friday appointments.</li></ul></div></div></div></section>
<section style={{background: 'var(--bg-green-tint)', padding: '80px 0'}}><div className="wrap" style={{display: 'flex', justifyContent: 'center'}}><div style={{maxWidth: '560px', background: 'var(--blue-deep)', borderRadius: '16px', padding: '48px', color: '#fff'}}><span style={{fontFamily: 'var(--mono)', fontSize: '11px', letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--green)', fontWeight: '700', display: 'block', marginBottom: '24px'}}>The 60-Day Profit Challenge &mdash; Guarantee</span><div style={{fontSize: 'clamp(52px, 7vw, 80px)', fontWeight: '900', fontFamily: 'var(--sans)', lineHeight: '1', color: '#fff', letterSpacing: '-.04em', marginBottom: '24px'}}>$20,000</div><p style={{fontSize: '17px', lineHeight: '1.7', color: 'rgba(255,255,255,0.88)', marginBottom: '32px'}}>If you do not add $20,000 in new salon revenue within 60 days, I keep working with you &mdash; live, 1-on-1 &mdash; for free until you do. No service credit. No conditions. I work for free until the number is hit.</p><div className="actions"><a className="btn btn--primary" href="/apply/">Apply Now &rarr;</a><a className="btn btn--ghost-invert" href="/the-challenge/">See everything in the Challenge</a></div></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common questions</span><h2 style={{marginTop: '14px'}}>From salon owners.</h2></div></div><FaqAccordion><div className="faq-item open"><button className="faq-q"><span className="qnum">Q.01</span><span className="qtxt">What exactly is the 60-Day Profit Challenge?</span><span className="qicn">+</span></button><div className="faq-a">The 60-Day Profit Challenge is a live, 1-on-1 business growth program for salon and spa owners. Over 60 days, we work through your offer, client acquisition, no-show reduction, retention, and referral engine &mdash; together, in live sessions, built around your specific business. Not a course. Not a software subscription. Real strategy, real work.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.02</span><span className="qtxt">What does the Challenge focus on for salons specifically?</span><span className="qicn">+</span></button><div className="faq-a">For salons and spas, the Challenge focuses on the three numbers that run the business: bookings (getting more of the right clients in the chair), no-shows (the fastest revenue recovery in most salons), and reviews (the compound growth engine that makes every new client easier to earn). We have worked with salon owners across the country and the playbook is built for how a solo stylist or small team actually operates.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.03</span><span className="qtxt">Is this a course or a done-for-you service?</span><span className="qicn">+</span></button><div className="faq-a">Neither &mdash; it is a working engagement. We build the actual growth strategy for your salon, install the systems, and stay in live sessions until $20,000 in new revenue is added. You are not watching videos. You are building with a real operator.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.04</span><span className="qtxt">What happens if I don&rsquo;t hit $20,000 in 60 days?</span><span className="qicn">+</span></button><div className="faq-a">If you do not add $20,000 in new revenue within 60 days, I keep working with you &mdash; live, 1-on-1 &mdash; for free until you do. No service credit. No conditions. I work for free until the number is hit.</div></div></FaqAccordion></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Ready to add $20,000 in new <em>salon revenue</em>?</h2><p className="sub">Apply to see if your salon qualifies. First conversation is free.</p><div className="actions"><a className="btn btn--invert" href="/apply/">Apply Now &rarr;</a></div></div></section>
    </main>
  );
}
