import FaqAccordion from '../../components/FaqAccordion';

export const metadata = {
  title: 'AI Automation for HVAC & Plumbing Companies in Kansas City | S.Y.S.T.E.M. KC',
  description: 'Missed-call text-back, quote follow-up, and review automation for Kansas City HVAC, plumbing and home-services companies. Recover 3–5 jobs a week from voicemail.',
};

export default function Page() {
  return (
    <main>
<div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">·</span><a href="/">Industries</a><span className="sep">·</span><span className="here">HVAC, Plumbing & Home Services</span></div></div>
<header className="page-hero"><div className="wrap"><span className="label">For HVAC, Plumbing & Home Services · Kansas City</span><h1>AI automation for <em>HVAC &amp; plumbing</em> companies in Kansas City.</h1><p className="lede">Trades businesses lose 3–5 jobs a week to slow phones and missed follow-ups. Most owners have no idea — they are on a roof. We fix that. Local, in-person, with a stack tuned to how your shop actually runs.</p><div className="actions"><a className="btn btn--primary" href="/contact/">Book a 20-min call <span className="arrow">→</span></a><a className="btn btn--ghost" href="#automations">See what we build</a></div></div></header>
<section className="section"><div className="wrap"><div className="prose" style={{maxWidth: '72ch'}}><h2 style={{marginTop: '0'}}>The lead loss problem (specific to trades).</h2><p>You are under a sink. The phone rings. By the time you towel off and call back, that homeowner has already booked your competitor. <strong>Industry research puts the missed-call rate for small home-services businesses at 62%</strong> — and 85% of those callers never try you again.</p><p>Add to that: quote follow-up that lives on sticky notes. Reviews that "we keep meaning to ask for." A scheduling system that is really just whoever happens to be in the office that day.</p><p>None of this is a moral failing. You are running a trades business — you are <em>supposed</em> to be on job sites. The leak is structural: there is no system handling the inbound while you are swinging a wrench. That is exactly what we build.</p></div></div></section>
<section className="section section--alt" id="automations"><div className="wrap"><div className="section-head"><div><span className="label">What we build for home-services</span><h2 style={{marginTop: '14px'}}>Built for trades shops with 1–20 trucks.</h2></div></div><div className="card-grid"><div className="card"><span className="tag">01 · Phone</span><h3>Missed-call text-back</h3><p>Every missed call triggers a personalized text within 30 seconds — "Sorry we missed you, can we help? Reply YES to book." Recovers 30–50% of missed-call jobs in our KC clients.</p></div><div className="card"><span className="tag">02 · Quotes</span><h3>Quote follow-up sequence</h3><p>Quote sent → automated check-in at +2 hours, +24 hours, +3 days, +7 days. Stops quotes from going cold while you are mid-job.</p></div><div className="card"><span className="tag">03 · Schedule</span><h3>Appointment confirmation flow</h3><p>Next-day job? Customer gets a confirmation text at 4pm the day before with the tech name and ETA window. Cuts day-of phone tag to zero.</p></div><div className="card"><span className="tag">04 · Reputation</span><h3>Review request automation</h3><p>Morning after every completed job — text first, email backup, direct Google Business Profile link. Pushes most clients past competitors in the local map pack.</p></div><div className="card"><span className="tag">05 · Dispatch</span><h3>Internal job-handoff alerts</h3><p>New booking? Tech gets a text. Job complete? Office gets a ping. No more "wait, who took that call?"</p></div><div className="card"><span className="tag">06 · Marketing</span><h3>Maintenance plan reminders</h3><p>Annual tune-up due? Automated sequence books it 60 days in advance. Recurring revenue without lifting a phone.</p></div></div></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="label">A day in the life</span><h2 style={{marginTop: '14px'}}>A 6-truck HVAC shop, 90 days in.</h2></div></div><div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '48px'}}><div><h3 style={{fontFamily: 'var(--mono)', fontSize: '13px', letterSpacing: '.12em', color: '#D4322E', textTransform: 'uppercase', fontWeight: '700'}}>Before</h3><ul style={{marginLeft: '18px', color: 'var(--text)', fontSize: '17px', lineHeight: '1.7'}}><li>Phone rings; voicemail picks up.</li><li>Owner checks voicemails on the drive home.</li><li>Five quotes sitting unsent in the inbox.</li><li>Reviews? Whoever the front-desk person feels like asking.</li><li>Owner working 12-hour days. Spouse is over it.</li></ul></div><div><h3 style={{fontFamily: 'var(--mono)', fontSize: '13px', letterSpacing: '.12em', color: '#1F8A99', textTransform: 'uppercase', fontWeight: '700'}}>After</h3><ul style={{marginLeft: '18px', color: 'var(--text)', fontSize: '17px', lineHeight: '1.7'}}><li>Missed call → text in 30 sec. Customer books online.</li><li>Quote auto-followed up four times across a week.</li><li>Job completes → review request fires the next morning.</li><li>Owner sees the day's booking summary on his phone at 7pm.</li><li>$31k/mo added revenue. New 7th truck. Owner home by 6.</li></ul></div></div></div></section>
<section className="section section--alt"><div className="wrap"><div className="section-head"><div><span className="label">Common questions</span><h2 style={{marginTop: '14px'}}>From home-services owners.</h2></div></div><FaqAccordion><div className="faq-item open"><button className="faq-q"><span className="qnum">Q.01</span><span className="qtxt">Do you work with my field-management software?</span><span className="qicn">+</span></button><div className="faq-a">We work with the major ones — and a few of the obscure ones. If yours has a webhook or an API, we can integrate. If it does not, we work around it.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.02</span><span className="qtxt">Will this replace my dispatcher?</span><span className="qicn">+</span></button><div className="faq-a">No. It makes your dispatcher 3x more effective. Automation handles the busywork (texts, reminders, confirmations) so your humans can focus on the real decisions.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.03</span><span className="qtxt">How long until I see results?</span><span className="qicn">+</span></button><div className="faq-a">Most KC trades clients see their first recovered missed-call job inside the first week. Full system rollout takes 2–4 weeks.</div></div><div className="faq-item"><button className="faq-q"><span className="qnum">Q.04</span><span className="qtxt">What does this typically cost?</span><span className="qicn">+</span></button><div className="faq-a">Audits are $397. Builds for a trades shop typically run $1,500–$4,000 fixed-bid. Retainers from $450/mo — covers your subscriptions too.</div></div></FaqAccordion></div></section>
<section className="cta-strip"><div className="wrap inner"><h2>Stop losing jobs to <em>voicemail</em>.</h2><p className="sub">$397 in-person audit. We come to your shop, find the 3 biggest leaks, and you walk away with a ranked plan. Yours whether you hire us to build it or not.</p><div className="actions"><a className="btn btn--invert" href="/contact/">Book the audit <span className="arrow">→</span></a></div></div></section>
    </main>
  );
}